// 20 Demo Users for Testing with comprehensive data

export interface DemoUser {
  id: string;
  name: string;
  age: number;
  role: "nannies" | "playdates" | "animal-lovers";
  bio: string;
  education?: string;
  degree?: string;
  height?: number;
  occupation?: string;
  isVerified: boolean;
  hasCar: boolean;
  isPremium: boolean;
  gender: string;
  orientation?: string;
  languages: string[];
  petExperience: string[];
  experienceYears: number;
  relationshipStatus?: string;
  avatarUrl?: string;
  location: { lat: number; lng: number };
  locationName: string;
  isOnline: boolean;
  postedToThreads?: boolean;
  pets: Array<{
    id: string;
    name: string;
    species: string;
    breed?: string;
    photoUrl?: string;
    age?: number;
  }>;
}

export interface DemoAlert {
  id: string;
  type: "Stray" | "Lost" | "Found" | "Others";
  description: string;
  latitude: number;
  longitude: number;
  location?: { lat: number; lng: number };
  photoUrl?: string;
  supportCount: number;
  reportCount: number;
  createdAt: string;
  creatorId: string;
  isActive: boolean;
  threadId?: string;
  postedToThreads?: boolean;
}

export interface DemoThread {
  id: string;
  title: string;
  content: string;
  tags: string[];
  hashtags: string[];
  images: string[];
  created_at: string;
  user_id: string;
  author: {
    display_name: string | null;
    avatar_url: string | null;
    is_verified: boolean;
  } | null;
}

// 20 Demo Users with comprehensive data - mix of roles and attributes
export const demoUsers: DemoUser[] = [
  {
    id: "demo-user-1",
    name: "Sarah Chen",
    age: 28,
    role: "nannies",
    bio: "Professional pet sitter with 5+ years of experience. Certified in pet first-aid. Available for overnight stays.",
    education: "University of Hong Kong",
    degree: "Bachelor",
    height: 165,
    occupation: "Professional Pet Sitter",
    isVerified: true,
    hasCar: true,
    isPremium: true,
    gender: "Female",
    orientation: "Straight",
    languages: ["English", "Cantonese", "Mandarin"],
    petExperience: ["Dogs", "Cats", "Small Mammals"],
    experienceYears: 5,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
    location: { lat: 22.2855, lng: 114.1577 },
    locationName: "Central, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-1a", name: "Mochi", species: "dog", breed: "Shiba Inu", age: 3 },
    ],
  },
  {
    id: "demo-user-2",
    name: "Marcus Wong",
    age: 32,
    role: "playdates",
    bio: "Software engineer and dog dad. Love hiking with my Golden Retriever. Looking for playdate buddies!",
    education: "HKUST",
    degree: "Master",
    height: 178,
    occupation: "Software Engineer",
    isVerified: false,
    hasCar: true,
    isPremium: false,
    gender: "Male",
    orientation: "Gay/Lesbian",
    languages: ["English", "Cantonese"],
    petExperience: ["Dogs"],
    experienceYears: 4,
    relationshipStatus: "In a relationship",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
    location: { lat: 22.2956, lng: 114.1722 },
    locationName: "Wan Chai, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-2a", name: "Charlie", species: "dog", breed: "Golden Retriever", age: 4 },
    ],
  },
  {
    id: "demo-user-3",
    name: "Emily Lam",
    age: 25,
    role: "animal-lovers",
    bio: "Animal shelter volunteer. Passionate about rescue animals and adoption advocacy. Let's connect!",
    education: "City University",
    degree: "Bachelor",
    height: 160,
    occupation: "Shelter Volunteer",
    isVerified: true,
    hasCar: false,
    isPremium: false,
    gender: "Female",
    orientation: "Bisexual",
    languages: ["English", "Cantonese", "Mandarin"],
    petExperience: ["Dogs", "Cats", "Birds", "Reptiles"],
    experienceYears: 3,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
    location: { lat: 22.2783, lng: 114.1747 },
    locationName: "Admiralty, Hong Kong",
    isOnline: false,
    pets: [],
  },
  {
    id: "demo-user-4",
    name: "James Liu",
    age: 35,
    role: "nannies",
    bio: "Nurse with flexible schedule. Certified in pet first-aid. Experienced with senior pets and special needs animals.",
    education: "Queen Mary Hospital School of Nursing",
    degree: "Bachelor",
    height: 175,
    occupation: "Registered Nurse",
    isVerified: true,
    hasCar: true,
    isPremium: true,
    gender: "Male",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Dogs", "Cats"],
    experienceYears: 8,
    relationshipStatus: "Married",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
    location: { lat: 22.3193, lng: 114.1694 },
    locationName: "Kowloon, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-4a", name: "Whiskers", species: "cat", breed: "British Shorthair", age: 7 },
    ],
  },
  {
    id: "demo-user-5",
    name: "Jessica Ng",
    age: 29,
    role: "playdates",
    bio: "Corgi mom x2! Always looking for Corgi playdate friends. My babies love making new friends.",
    education: "HKU",
    degree: "Master",
    height: 163,
    occupation: "Marketing Manager",
    isVerified: false,
    hasCar: false,
    isPremium: false,
    gender: "Female",
    orientation: "Straight",
    languages: ["English", "Cantonese", "Japanese"],
    petExperience: ["Dogs"],
    experienceYears: 5,
    relationshipStatus: "In a relationship",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
    location: { lat: 22.2799, lng: 114.1829 },
    locationName: "Causeway Bay, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-5a", name: "Coco", species: "dog", breed: "Corgi", age: 2 },
      { id: "pet-5b", name: "Latte", species: "dog", breed: "Corgi", age: 2 },
    ],
  },
  {
    id: "demo-user-6",
    name: "David Chan",
    age: 45,
    role: "animal-lovers",
    bio: "PhD in Zoology. Bird enthusiast with 20+ years of aviculture experience. Happy to advise on bird care.",
    education: "Stanford University",
    degree: "Doctorate / PhD",
    height: 172,
    occupation: "University Professor",
    isVerified: true,
    hasCar: true,
    isPremium: true,
    gender: "Male",
    orientation: "PNA",
    languages: ["English", "Cantonese", "Mandarin", "French"],
    petExperience: ["Birds", "Fish", "Reptiles"],
    experienceYears: 20,
    relationshipStatus: "Married",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    location: { lat: 22.3364, lng: 114.1747 },
    locationName: "Mong Kok, Hong Kong",
    isOnline: false,
    pets: [
      { id: "pet-6a", name: "Phoenix", species: "bird", breed: "African Grey Parrot", age: 12 },
      { id: "pet-6b", name: "Sunny", species: "bird", breed: "Cockatiel", age: 5 },
    ],
  },
  {
    id: "demo-user-7",
    name: "Amy Tsang",
    age: 31,
    role: "nannies",
    bio: "Professional pet groomer. Can do grooming while pet-sitting! Specializing in small dogs and cats.",
    education: "Pet Grooming Academy",
    degree: "Associate Degree",
    height: 158,
    occupation: "Pet Groomer",
    isVerified: false,
    hasCar: true,
    isPremium: false,
    gender: "Female",
    orientation: "Queer",
    languages: ["Cantonese", "Mandarin"],
    petExperience: ["Dogs", "Cats", "Small Mammals"],
    experienceYears: 7,
    relationshipStatus: "Open relationship",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200",
    location: { lat: 22.3080, lng: 114.2554 },
    locationName: "Tseung Kwan O, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-7a", name: "Bella", species: "cat", breed: "Persian", age: 4 },
    ],
  },
  {
    id: "demo-user-8",
    name: "Kevin Ho",
    age: 27,
    role: "playdates",
    bio: "French Bulldog enthusiast! My Frenchie loves beach walks and café hopping. Weekend playdate partners welcome!",
    education: "PolyU",
    degree: "Bachelor",
    height: 180,
    occupation: "Financial Analyst",
    isVerified: false,
    hasCar: false,
    isPremium: false,
    gender: "Male",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Dogs"],
    experienceYears: 3,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
    location: { lat: 22.2397, lng: 114.1715 },
    locationName: "Aberdeen, Hong Kong",
    isOnline: false,
    pets: [
      { id: "pet-8a", name: "Bruno", species: "dog", breed: "French Bulldog", age: 2 },
    ],
  },
  {
    id: "demo-user-9",
    name: "Michelle Yip",
    age: 24,
    role: "animal-lovers",
    bio: "Cat café regular and foster mom. Specializing in kitten socialization. Currently fostering 3 rescue kittens!",
    education: "Baptist University",
    degree: "Bachelor",
    height: 162,
    occupation: "Graphic Designer",
    isVerified: false,
    hasCar: false,
    isPremium: false,
    gender: "Female",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Cats"],
    experienceYears: 4,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
    location: { lat: 22.2868, lng: 114.1413 },
    locationName: "Sheung Wan, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-9a", name: "Mimi", species: "cat", breed: "Tabby", age: 1 },
      { id: "pet-9b", name: "Kiki", species: "cat", breed: "Calico", age: 1 },
    ],
  },
  {
    id: "demo-user-10",
    name: "Tom Lee",
    age: 55,
    role: "nannies",
    bio: "Retired vet tech with 25 years experience. Can administer medications. Perfect for pets needing extra medical attention.",
    education: "Ontario Veterinary College",
    degree: "Associate Degree",
    height: 170,
    occupation: "Retired Vet Tech",
    isVerified: true,
    hasCar: true,
    isPremium: false,
    gender: "Male",
    orientation: "Straight",
    languages: ["English", "Cantonese", "Mandarin"],
    petExperience: ["Dogs", "Cats", "Birds", "Fish", "Reptiles", "Small Mammals"],
    experienceYears: 25,
    relationshipStatus: "Divorced",
    avatarUrl: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=200",
    location: { lat: 22.3526, lng: 114.1392 },
    locationName: "Sham Shui Po, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-10a", name: "Max", species: "dog", breed: "Labrador", age: 10 },
      { id: "pet-10b", name: "Luna", species: "cat", breed: "Maine Coon", age: 6 },
    ],
  },
  {
    id: "demo-user-11",
    name: "Ava Lau",
    age: 26,
    role: "playdates",
    bio: "Husky mom who loves weekend hikes. Looking for energetic playmates for my pup.",
    education: "Hong Kong University",
    degree: "Bachelor",
    height: 168,
    occupation: "UX Designer",
    isVerified: false,
    hasCar: false,
    isPremium: false,
    gender: "Female",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Dogs"],
    experienceYears: 2,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
    location: { lat: 22.3027, lng: 114.1772 },
    locationName: "Tsim Sha Tsui, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-11a", name: "Nova", species: "dog", breed: "Siberian Husky", age: 2 },
    ],
  },
  {
    id: "demo-user-12",
    name: "Brian Kwok",
    age: 38,
    role: "nannies",
    bio: "Certified pet trainer with boarding experience. Comfortable with large dogs and senior pets.",
    education: "HKU SPACE",
    degree: "Diploma",
    height: 176,
    occupation: "Pet Trainer",
    isVerified: true,
    hasCar: true,
    isPremium: true,
    gender: "Male",
    orientation: "Straight",
    languages: ["English", "Cantonese", "Mandarin"],
    petExperience: ["Dogs", "Cats"],
    experienceYears: 9,
    relationshipStatus: "Married",
    avatarUrl: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=200",
    location: { lat: 22.3219, lng: 114.1690 },
    locationName: "Mong Kok, Hong Kong",
    isOnline: false,
    pets: [
      { id: "pet-12a", name: "Rex", species: "dog", breed: "German Shepherd", age: 5 },
    ],
  },
  {
    id: "demo-user-13",
    name: "Chloe Fung",
    age: 31,
    role: "animal-lovers",
    bio: "Rescue advocate and foster parent. Happy to connect and share adoption tips.",
    education: "Lingnan University",
    degree: "Master",
    height: 164,
    occupation: "Project Manager",
    isVerified: false,
    hasCar: false,
    isPremium: false,
    gender: "Female",
    orientation: "Bisexual",
    languages: ["English", "Cantonese"],
    petExperience: ["Cats", "Small Mammals"],
    experienceYears: 6,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
    location: { lat: 22.3370, lng: 114.1440 },
    locationName: "Kwai Chung, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-13a", name: "Bean", species: "cat", breed: "Domestic Shorthair", age: 3 },
    ],
  },
  {
    id: "demo-user-14",
    name: "Daniel Tse",
    age: 29,
    role: "playdates",
    bio: "First-time dog dad. My corgi is friendly and loves beach days.",
    education: "HKU",
    degree: "Bachelor",
    height: 174,
    occupation: "Product Analyst",
    isVerified: false,
    hasCar: true,
    isPremium: false,
    gender: "Male",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Dogs"],
    experienceYears: 1,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    location: { lat: 22.2810, lng: 114.1600 },
    locationName: "Central, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-14a", name: "Biscuit", species: "dog", breed: "Corgi", age: 1 },
    ],
  },
  {
    id: "demo-user-15",
    name: "Ethan Mak",
    age: 41,
    role: "nannies",
    bio: "Former zookeeper. Experienced with exotics and reptiles. Available for short-term boarding.",
    education: "University of Melbourne",
    degree: "Bachelor",
    height: 182,
    occupation: "Animal Care Specialist",
    isVerified: true,
    hasCar: true,
    isPremium: true,
    gender: "Male",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Reptiles", "Birds", "Small Mammals"],
    experienceYears: 12,
    relationshipStatus: "Married",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
    location: { lat: 22.3720, lng: 114.1180 },
    locationName: "Tsuen Wan, Hong Kong",
    isOnline: false,
    pets: [
      { id: "pet-15a", name: "Rio", species: "bird", breed: "Macaw", age: 4 },
    ],
  },
  {
    id: "demo-user-16",
    name: "Fiona Cheung",
    age: 34,
    role: "animal-lovers",
    bio: "Volunteer at SPCA. Love connecting pet parents with trusted resources.",
    education: "City University",
    degree: "Bachelor",
    height: 161,
    occupation: "Community Manager",
    isVerified: false,
    hasCar: false,
    isPremium: false,
    gender: "Female",
    orientation: "Straight",
    languages: ["English", "Cantonese", "Mandarin"],
    petExperience: ["Dogs", "Cats"],
    experienceYears: 7,
    relationshipStatus: "In a relationship",
    avatarUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=200",
    location: { lat: 22.2990, lng: 114.1720 },
    locationName: "Jordan, Hong Kong",
    isOnline: true,
    pets: [],
  },
  {
    id: "demo-user-17",
    name: "Grace Ip",
    age: 22,
    role: "playdates",
    bio: "University student with a playful beagle. Looking for puppy buddies.",
    education: "HKU",
    degree: "Undergraduate",
    height: 158,
    occupation: "Student",
    isVerified: false,
    hasCar: false,
    isPremium: false,
    gender: "Female",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Dogs"],
    experienceYears: 1,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=200",
    location: { lat: 22.3165, lng: 114.1700 },
    locationName: "Prince Edward, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-17a", name: "Scout", species: "dog", breed: "Beagle", age: 1 },
    ],
  },
  {
    id: "demo-user-18",
    name: "Henry Ng",
    age: 47,
    role: "nannies",
    bio: "Night-shift sitter with experience in medication schedules and senior care.",
    education: "Open University",
    degree: "Diploma",
    height: 173,
    occupation: "Caregiver",
    isVerified: true,
    hasCar: false,
    isPremium: true,
    gender: "Male",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Dogs", "Cats"],
    experienceYears: 15,
    relationshipStatus: "Married",
    avatarUrl: "https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=200",
    location: { lat: 22.2850, lng: 114.1930 },
    locationName: "Causeway Bay, Hong Kong",
    isOnline: false,
    pets: [
      { id: "pet-18a", name: "Shadow", species: "cat", breed: "Russian Blue", age: 8 },
    ],
  },
  {
    id: "demo-user-19",
    name: "Ivy Tam",
    age: 30,
    role: "animal-lovers",
    bio: "Animal photographer. Happy to share pet-friendly spots and tips.",
    education: "PolyU",
    degree: "Bachelor",
    height: 165,
    occupation: "Photographer",
    isVerified: false,
    hasCar: true,
    isPremium: false,
    gender: "Female",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Dogs", "Cats", "Birds"],
    experienceYears: 5,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
    location: { lat: 22.2780, lng: 114.1850 },
    locationName: "North Point, Hong Kong",
    isOnline: true,
    pets: [
      { id: "pet-19a", name: "Milo", species: "dog", breed: "Poodle", age: 4 },
    ],
  },
  {
    id: "demo-user-20",
    name: "Jacky Poon",
    age: 27,
    role: "playdates",
    bio: "Active runner with a border collie. Happy to meet for runs and training sessions.",
    education: "HKUST",
    degree: "Bachelor",
    height: 179,
    occupation: "Sales Manager",
    isVerified: false,
    hasCar: true,
    isPremium: false,
    gender: "Male",
    orientation: "Straight",
    languages: ["English", "Cantonese"],
    petExperience: ["Dogs"],
    experienceYears: 3,
    relationshipStatus: "Single",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    location: { lat: 22.3390, lng: 114.1600 },
    locationName: "Cheung Sha Wan, Hong Kong",
    isOnline: false,
    pets: [
      { id: "pet-20a", name: "Dash", species: "dog", breed: "Border Collie", age: 3 },
    ],
  },
];

demoUsers.forEach((u) => {
  u.postedToThreads = true;
});

// Demo alerts for map — Spec: 10 Stray (blue paw 🐾) + 10 Lost (red alert 🚨)
export const demoAlerts: DemoAlert[] = [
  // ===== 10 STRAY ALERTS =====
  {
    id: "stray-1",
    type: "Stray",
    description: "Friendly stray dog spotted near Central Ferry Pier. Black and white, medium size. Looks well-fed but no collar.",
    latitude: 22.2855,
    longitude: 114.1577,
    location: { lat: 22.2855, lng: 114.1577 },
    photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
    supportCount: 15,
    reportCount: 0,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-1",
    isActive: true,
  },
  {
    id: "stray-2",
    type: "Stray",
    description: "Group of stray cats near Wan Chai Market. About 4-5 cats. Someone has been feeding them regularly.",
    latitude: 22.2780,
    longitude: 114.1730,
    location: { lat: 22.2780, lng: 114.1730 },
    supportCount: 32,
    reportCount: 1,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-4",
    isActive: true,
  },
  {
    id: "stray-3",
    type: "Stray",
    description: "Small stray puppy seen near Tsim Sha Tsui Star Ferry terminal. Brown fur, timid but approachable.",
    latitude: 22.2933,
    longitude: 114.1688,
    location: { lat: 22.2933, lng: 114.1688 },
    photoUrl: "https://images.unsplash.com/photo-1583337130417-13219ce08108?w=400",
    supportCount: 22,
    reportCount: 0,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-5",
    isActive: true,
  },
  {
    id: "stray-4",
    type: "Stray",
    description: "Stray ginger cat hanging around Mong Kok flower market area. Appears healthy, very vocal.",
    latitude: 22.3219,
    longitude: 114.1690,
    location: { lat: 22.3219, lng: 114.1690 },
    supportCount: 18,
    reportCount: 0,
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-12",
    isActive: true,
  },
  {
    id: "stray-5",
    type: "Stray",
    description: "Two stray dogs near Aberdeen promenade. One is limping, may need medical attention.",
    latitude: 22.2480,
    longitude: 114.1556,
    location: { lat: 22.2480, lng: 114.1556 },
    photoUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
    supportCount: 41,
    reportCount: 0,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-8",
    isActive: true,
  },
  {
    id: "stray-6",
    type: "Stray",
    description: "Stray cat colony near Sham Shui Po wet market. About 8 cats. Need volunteers to help with TNR.",
    latitude: 22.3310,
    longitude: 114.1596,
    location: { lat: 22.3310, lng: 114.1596 },
    supportCount: 56,
    reportCount: 0,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-10",
    isActive: true,
  },
  {
    id: "stray-7",
    type: "Stray",
    description: "Young stray kitten found behind IFC mall loading dock. Needs foster home urgently.",
    latitude: 22.2852,
    longitude: 114.1583,
    location: { lat: 22.2852, lng: 114.1583 },
    photoUrl: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=400",
    supportCount: 67,
    reportCount: 0,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-9",
    isActive: true,
  },
  {
    id: "stray-8",
    type: "Stray",
    description: "Stray dog near Tseung Kwan O waterfront park. Friendly, seems to be abandoned. Medium-large size.",
    latitude: 22.3080,
    longitude: 114.2554,
    location: { lat: 22.3080, lng: 114.2554 },
    supportCount: 14,
    reportCount: 0,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-7",
    isActive: true,
  },
  {
    id: "stray-9",
    type: "Stray",
    description: "Stray cat family under bridge near Kwai Chung estate. Mother cat with 3 kittens.",
    latitude: 22.3570,
    longitude: 114.1270,
    location: { lat: 22.3570, lng: 114.1270 },
    supportCount: 38,
    reportCount: 0,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-13",
    isActive: true,
  },
  {
    id: "stray-10",
    type: "Stray",
    description: "Elderly stray dog near Cheung Sha Wan park. Grey muzzle, walks slowly. Could use some food and water.",
    latitude: 22.3390,
    longitude: 114.1600,
    location: { lat: 22.3390, lng: 114.1600 },
    photoUrl: "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400",
    supportCount: 29,
    reportCount: 0,
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-20",
    isActive: true,
  },

  // ===== 10 LOST ALERTS =====
  {
    id: "lost-1",
    type: "Lost",
    description: "Lost golden retriever near Victoria Park. Answers to 'Buddy'. Very friendly. Reward offered!",
    latitude: 22.2820,
    longitude: 114.1880,
    location: { lat: 22.2820, lng: 114.1880 },
    photoUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400",
    supportCount: 45,
    reportCount: 0,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-2",
    isActive: true,
  },
  {
    id: "lost-2",
    type: "Lost",
    description: "Missing tabby cat. Last seen near Sheung Wan MTR. Has a blue collar with name tag 'Mochi'.",
    latitude: 22.2868,
    longitude: 114.1413,
    location: { lat: 22.2868, lng: 114.1413 },
    photoUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400",
    supportCount: 28,
    reportCount: 0,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-9",
    isActive: true,
  },
  {
    id: "lost-3",
    type: "Lost",
    description: "Lost white Pomeranian near Causeway Bay Times Square. Name: Snowball. Wearing pink harness. Please call if seen!",
    latitude: 22.2799,
    longitude: 114.1829,
    location: { lat: 22.2799, lng: 114.1829 },
    photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
    supportCount: 72,
    reportCount: 0,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-5",
    isActive: true,
  },
  {
    id: "lost-4",
    type: "Lost",
    description: "Missing Siamese cat from Jordan area. Blue eyes, cream body. Indoor cat that escaped. Very scared.",
    latitude: 22.3050,
    longitude: 114.1710,
    location: { lat: 22.3050, lng: 114.1710 },
    supportCount: 35,
    reportCount: 0,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-16",
    isActive: true,
  },
  {
    id: "lost-5",
    type: "Lost",
    description: "Lost Shiba Inu near Prince Edward MTR station. Red/orange colour, curly tail. Answers to 'Mochi'.",
    latitude: 22.3270,
    longitude: 114.1685,
    location: { lat: 22.3270, lng: 114.1685 },
    photoUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400",
    supportCount: 53,
    reportCount: 0,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-1",
    isActive: true,
  },
  {
    id: "lost-6",
    type: "Lost",
    description: "Missing black Labrador from North Point area. Large, neutered male. Has microchip. Very gentle.",
    latitude: 22.2910,
    longitude: 114.2001,
    location: { lat: 22.2910, lng: 114.2001 },
    supportCount: 41,
    reportCount: 0,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-19",
    isActive: true,
  },
  {
    id: "lost-7",
    type: "Lost",
    description: "Lost parrot (African Grey) flew away from balcony in Tsuen Wan. Can say 'Hello' and 'Good boy'.",
    latitude: 22.3720,
    longitude: 114.1180,
    location: { lat: 22.3720, lng: 114.1180 },
    supportCount: 89,
    reportCount: 0,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-6",
    isActive: true,
  },
  {
    id: "lost-8",
    type: "Lost",
    description: "Missing Corgi from Admiralty. Short legs, tri-colour. Escaped during walk. Has blue collar.",
    latitude: 22.2783,
    longitude: 114.1647,
    location: { lat: 22.2783, lng: 114.1647 },
    photoUrl: "https://images.unsplash.com/photo-1612536057832-2ff7ead58194?w=400",
    supportCount: 61,
    reportCount: 0,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    creatorId: "demo-user-14",
    isActive: true,
  },
  {
    id: "lost-9",
    type: "Lost",
    description: "Lost Russian Blue cat near Happy Valley. Indoor cat, very shy. Grey coat, green eyes. May be hiding under cars.",
    latitude: 22.2713,
    longitude: 114.1830,
    location: { lat: 22.2713, lng: 114.1830 },
    supportCount: 33,
    reportCount: 0,
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-18",
    isActive: true,
  },
  {
    id: "lost-10",
    type: "Lost",
    description: "Missing French Bulldog from Kowloon Tong area. Brindle colour, answers to 'Bruno'. Wearing red bow tie.",
    latitude: 22.3364,
    longitude: 114.1747,
    location: { lat: 22.3364, lng: 114.1747 },
    photoUrl: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400",
    supportCount: 47,
    reportCount: 0,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-8",
    isActive: true,
  },

  // ===== 5 OTHERS ALERTS (grey paw ℹ️) =====
  {
    id: "others-1",
    type: "Others",
    description: "Injured bird spotted in Kowloon Park. Appears to be a dove with an injured wing. Needs help!",
    latitude: 22.3030,
    longitude: 114.1710,
    location: { lat: 22.3030, lng: 114.1710 },
    supportCount: 12,
    reportCount: 0,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-6",
    isActive: true,
  },
  {
    id: "others-2",
    type: "Others",
    description: "Free pet food giveaway near Tai Koo MTR exit A. First come first served. Dry food and treats.",
    latitude: 22.2890,
    longitude: 114.2165,
    location: { lat: 22.2890, lng: 114.2165 },
    supportCount: 34,
    reportCount: 0,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-3",
    isActive: true,
  },
  {
    id: "others-3",
    type: "Others",
    description: "Pet-friendly cafe just opened near Lai Chi Kok. Dogs and cats welcome. Free pupuccino with purchase.",
    latitude: 22.3370,
    longitude: 114.1480,
    location: { lat: 22.3370, lng: 114.1480 },
    supportCount: 56,
    reportCount: 0,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-11",
    isActive: true,
  },
  {
    id: "others-4",
    type: "Others",
    description: "Animal adoption event this Saturday at Sha Tin Park. Multiple shelters participating. Bring ID.",
    latitude: 22.3815,
    longitude: 114.1920,
    location: { lat: 22.3815, lng: 114.1920 },
    supportCount: 78,
    reportCount: 0,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-15",
    isActive: true,
  },
  {
    id: "others-5",
    type: "Others",
    description: "Warning: Rat poison spotted near Quarry Bay Park playground. Keep pets away from the area.",
    latitude: 22.2880,
    longitude: 114.2112,
    location: { lat: 22.2880, lng: 114.2112 },
    supportCount: 91,
    reportCount: 0,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    creatorId: "demo-user-17",
    isActive: true,
  },
];

const demoThreadIdByAlert: Record<string, string> = {
  "stray-1": "9888a51c-eb39-418d-b779-b5171b1d399d",
  "stray-2": "2bd23e9b-9758-46fd-a807-4803a4ee12e7",
  "stray-3": "8dfe8ca2-7141-4465-b8a3-0f535e8fbd6b",
  "stray-4": "6ead51ff-33f7-450d-8122-38226b368924",
  "stray-5": "2bf80aea-6dec-4728-a21d-ee61b04536b7",
  "stray-6": "e8bc3c1d-c6cd-453d-89f2-1250662ab997",
  "stray-7": "5693eb81-1036-4902-826c-644e713b65e4",
  "stray-8": "f1d667ca-c495-457f-ad19-74aaca9c41bb",
  "stray-9": "f68abbe9-1ca8-4845-b43c-9d5cd19f7165",
  "stray-10": "18cf7406-d38f-47bf-aa86-0bdd5fc02924",
  "lost-1": "43a06dd1-0ce0-4854-8448-42dd905a4d18",
  "lost-2": "f6fe5d47-48f8-4c29-a065-5e1068ff0a09",
  "lost-3": "c4856dc0-2ff1-42b9-916a-560de967a8e1",
  "lost-4": "605143ad-6131-46f4-8aa5-8cb717ef14d0",
  "lost-5": "d06bc79a-c105-4bc3-baba-c0020baee022",
  "lost-6": "9eff8465-7454-40b8-a8d3-bb0deda1c024",
  "lost-7": "66f64fe6-1bc7-4f5a-ba59-b3c303fe59ae",
  "lost-8": "f2ac2b03-24ef-4c04-b645-938622f5edce",
  "lost-9": "c33ecb2c-c2b9-487d-8910-ffe71d3f30ba",
  "lost-10": "97f1a18a-e748-41d5-8ebf-f5e3768792b4",
  "others-1": "b6f5bb06-1f74-4b4c-9bdb-aefe7f5e1131",
  "others-2": "5b1df1e8-e80f-4f85-90d7-cd67c5a3f1f4",
  "others-3": "2f8d1629-31dd-4db2-a882-8f0cbfa7a4d6",
  "others-4": "ed305f81-a25e-4ecf-9ab8-03fb70a4c017",
  "others-5": "d74818f9-b3af-443d-9d7d-5634000414c6",
};

demoAlerts.forEach((alert) => {
  alert.threadId = demoThreadIdByAlert[alert.id];
  alert.postedToThreads = true;
});

export const demoThreads: DemoThread[] = demoAlerts.map((alert) => {
  const creator = demoUsers.find((u) => u.id === alert.creatorId);
  return {
    id: alert.threadId || demoThreadIdByAlert[alert.id],
    title: alert.type === "Others" ? "Community Notice" : `${alert.type} Alert`,
    content: alert.description,
    tags: [alert.type === "Others" ? "News" : "News"],
    hashtags: [],
    images: alert.photoUrl ? [alert.photoUrl] : [],
    created_at: alert.createdAt,
    user_id: alert.creatorId,
    author: creator
      ? { display_name: creator.name, avatar_url: creator.avatarUrl || null, is_verified: creator.isVerified }
      : null,
  };
});

// ===== 15 DEMO FRIEND PINS (Green Initial Icons on Map) =====
export interface DemoFriendPin {
  id: string;
  display_name: string;
  avatar_url: string | null;
  dob: string | null;
  relationship_status: string | null;
  owns_pets: boolean;
  pet_species: string[];
  location_name: string;
  last_lat: number;
  last_lng: number;
  location_pinned_until: string;
}

export const demoFriendPins: DemoFriendPin[] = [
  { id: "demo-user-1", display_name: "Sarah Chen", avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200", dob: "1997-03-15", relationship_status: "Single", owns_pets: true, pet_species: ["dog"], location_name: "Central, HK", last_lat: 22.2855, last_lng: 114.1577, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-2", display_name: "Marcus Wong", avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200", dob: "1993-07-22", relationship_status: "In a relationship", owns_pets: true, pet_species: ["dog"], location_name: "Wan Chai, HK", last_lat: 22.2956, last_lng: 114.1722, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-3", display_name: "Emily Lam", avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200", dob: "1999-01-20", relationship_status: "Single", owns_pets: false, pet_species: [], location_name: "Admiralty, HK", last_lat: 22.2783, last_lng: 114.1747, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-4", display_name: "James Liu", avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200", dob: "1990-01-10", relationship_status: "Married", owns_pets: true, pet_species: ["cat"], location_name: "Kowloon, HK", last_lat: 22.3193, last_lng: 114.1694, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-5", display_name: "Jessica Ng", avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200", dob: "1996-05-18", relationship_status: "In a relationship", owns_pets: true, pet_species: ["dog"], location_name: "Causeway Bay, HK", last_lat: 22.2799, last_lng: 114.1829, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-6", display_name: "David Chan", avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200", dob: "1979-10-02", relationship_status: "Married", owns_pets: true, pet_species: ["bird"], location_name: "Mong Kok, HK", last_lat: 22.3364, last_lng: 114.1747, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-7", display_name: "Amy Tsang", avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200", dob: "1994-09-08", relationship_status: "Open relationship", owns_pets: true, pet_species: ["cat"], location_name: "Tseung Kwan O, HK", last_lat: 22.3080, last_lng: 114.2554, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-8", display_name: "Kevin Ho", avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200", dob: "1998-03-12", relationship_status: "Single", owns_pets: true, pet_species: ["dog"], location_name: "Aberdeen, HK", last_lat: 22.2397, last_lng: 114.1715, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-9", display_name: "Michelle Yip", avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200", dob: "2001-02-14", relationship_status: "Single", owns_pets: true, pet_species: ["cat"], location_name: "Sheung Wan, HK", last_lat: 22.2868, last_lng: 114.1413, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-10", display_name: "Tom Lee", avatar_url: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=200", dob: "1969-11-05", relationship_status: "Divorced", owns_pets: true, pet_species: ["dog", "cat"], location_name: "Sham Shui Po, HK", last_lat: 22.3526, last_lng: 114.1392, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-11", display_name: "Ava Lau", avatar_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200", dob: "1999-11-30", relationship_status: "Single", owns_pets: true, pet_species: ["dog"], location_name: "Tsim Sha Tsui, HK", last_lat: 22.3027, last_lng: 114.1772, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-12", display_name: "Brian Kwok", avatar_url: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=200", dob: "1987-04-04", relationship_status: "Married", owns_pets: true, pet_species: ["dog"], location_name: "Mong Kok, HK", last_lat: 22.3219, last_lng: 114.1690, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-14", display_name: "Daniel Tse", avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200", dob: "1996-08-20", relationship_status: "Single", owns_pets: true, pet_species: ["dog"], location_name: "Central, HK", last_lat: 22.2810, last_lng: 114.1600, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-17", display_name: "Grace Ip", avatar_url: "https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=200", dob: "2003-06-12", relationship_status: "Single", owns_pets: true, pet_species: ["dog"], location_name: "Prince Edward, HK", last_lat: 22.3165, last_lng: 114.1700, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
  { id: "demo-user-19", display_name: "Ivy Tam", avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200", dob: "1995-04-25", relationship_status: "Single", owns_pets: true, pet_species: ["dog", "cat", "bird"], location_name: "North Point, HK", last_lat: 22.2780, last_lng: 114.1850, location_pinned_until: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString() },
];

// Helper functions
export const getVerifiedUsers = () => demoUsers.filter(u => u.isVerified);
export const getUsersWithCar = () => demoUsers.filter(u => u.hasCar);
export const getPremiumUsers = () => demoUsers.filter(u => u.isPremium);
export const getUsersWithPets = () => demoUsers.filter(u => u.pets.length > 0);
export const getOnlineUsers = () => demoUsers.filter(u => u.isOnline);
export const getUsersByRole = (role: DemoUser["role"]) => demoUsers.filter(u => u.role === role);

// Get demo user by ID
export const getDemoUser = (id: string): DemoUser | undefined => {
  return demoUsers.find(user => user.id === id);
};

// Filter demo users by role
export const getDemoUsersByRole = (role: DemoUser["role"]): DemoUser[] => {
  return demoUsers.filter(user => user.role === role);
};

// Get online demo users
export const getOnlineDemoUsers = (): DemoUser[] => {
  return demoUsers.filter(user => user.isOnline);
};
