project_id = "ztrbourwcnhrpmzwlrcn"

[functions.verify-device-fingerprint]
verify_jwt = false

[functions.verify-human-challenge]
verify_jwt = false

[functions.create-identity-setup-intent]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-stripe-connect-link]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
