import { StyleSheet } from "react-native";

export const huddleModalTokens = {
  color: {
    blue: "#2145CF",
    text: "#424965",
    mutedText: "rgba(74, 73, 101, 0.55)",
    validationRed: "#EF4444",
    canvas: "#FFFFFF",
    modalBackdrop: "rgba(227, 232, 243, 0.98)",
    fieldBorder: "rgba(163,168,190,0.24)",
    fieldFocusBorder: "rgba(33,69,207,0.62)",
    fieldFocusShadow: "rgba(33,69,207,0.22)",
    fieldErrorBorder: "rgba(232,69,69,0.72)",
    fieldErrorShadow: "rgba(232,69,69,0.22)",
    neutralShadow: "rgba(163, 168, 190, 0.28)",
    onPrimary: "#FFFFFF",
  },
  radius: {
    button: 14,
    field: 14,
    modal: 28,
    checkbox: 9,
  },
  spacing: {
    x1: 4,
    x2: 8,
    x3: 12,
    x4: 16,
    x5: 24,
    x7: 40,
  },
  size: {
    close: 44,
    minTouch: 44,
    fieldHeight: 52,
    textAreaHeight: 108,
    buttonHeight: 44,
    turnstileHeight: 74,
  },
  type: {
    titleFamily: "Urbanist-700",
    bodyFamily: "Urbanist-500",
    labelFamily: "Urbanist-600",
    buttonFamily: "Urbanist-700",
    titleSize: 22,
    titleLine: 28,
    inputSize: 16,
    inputLine: 22,
    labelSize: 12,
    labelLine: 16,
    helperSize: 12,
    helperLine: 16,
    subtextSize: 13,
    subtextLine: 18,
  },
} as const;

export const styles = StyleSheet.create({
  appModalBackdrop: {
    flex: 1,
    backgroundColor: huddleModalTokens.color.modalBackdrop,
  },
  appModalSafeArea: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: huddleModalTokens.spacing.x4,
  },
  appModalCard: {
    maxHeight: "88%",
    overflow: "hidden",
    borderRadius: huddleModalTokens.radius.modal,
    backgroundColor: huddleModalTokens.color.canvas,
    shadowColor: "#0057FF",
    shadowOpacity: 0.13,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  appModalCardFull: {
    flex: 1,
    overflow: "hidden",
    borderRadius: huddleModalTokens.radius.modal,
    backgroundColor: huddleModalTokens.color.canvas,
    shadowColor: "#0057FF",
    shadowOpacity: 0.13,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  appModalClose: {
    position: "absolute",
    top: huddleModalTokens.spacing.x3,
    right: huddleModalTokens.spacing.x3,
    zIndex: 5,
    width: huddleModalTokens.size.close,
    height: huddleModalTokens.size.close,
    alignItems: "center",
    justifyContent: "center",
  },
  appModalScrollContent: {
    padding: huddleModalTokens.spacing.x4,
    paddingTop: huddleModalTokens.spacing.x5,
    paddingBottom: huddleModalTokens.spacing.x7,
  },
  appModalPanel: {
    paddingHorizontal: huddleModalTokens.spacing.x4,
    paddingTop: huddleModalTokens.spacing.x4,
    paddingBottom: huddleModalTokens.spacing.x3,
    gap: huddleModalTokens.spacing.x4,
  },
  appModalTitle: {
    fontFamily: huddleModalTokens.type.titleFamily,
    fontSize: huddleModalTokens.type.titleSize,
    lineHeight: huddleModalTokens.type.titleLine,
    color: huddleModalTokens.color.text,
  },
  appModalLabel: {
    fontFamily: huddleModalTokens.type.labelFamily,
    fontSize: huddleModalTokens.type.labelSize,
    lineHeight: huddleModalTokens.type.labelLine,
    color: huddleModalTokens.color.text,
  },
  appModalFieldGroup: {
    gap: huddleModalTokens.spacing.x2,
  },
  appModalField: {
    minHeight: huddleModalTokens.size.fieldHeight,
    borderWidth: 1,
    borderColor: huddleModalTokens.color.fieldBorder,
    borderRadius: huddleModalTokens.radius.field,
    paddingHorizontal: huddleModalTokens.spacing.x4,
    fontFamily: huddleModalTokens.type.bodyFamily,
    fontSize: huddleModalTokens.type.inputSize,
    lineHeight: huddleModalTokens.type.inputLine,
    color: huddleModalTokens.color.text,
    backgroundColor: "rgba(255,255,255,0.88)",
    shadowColor: huddleModalTokens.color.neutralShadow,
    shadowOpacity: 0.8,
    shadowRadius: 16,
    shadowOffset: { width: 5, height: 5 },
    elevation: 1,
  },
  appModalFieldFocused: {
    borderColor: huddleModalTokens.color.fieldFocusBorder,
    shadowColor: huddleModalTokens.color.fieldFocusShadow,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  appModalFieldError: {
    borderColor: huddleModalTokens.color.fieldErrorBorder,
    shadowColor: huddleModalTokens.color.fieldErrorShadow,
    shadowOpacity: 1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  appModalTextArea: {
    height: huddleModalTokens.size.textAreaHeight,
    maxHeight: huddleModalTokens.size.textAreaHeight,
    paddingTop: huddleModalTokens.spacing.x3,
    paddingBottom: huddleModalTokens.spacing.x3,
  },
  appModalError: {
    fontFamily: huddleModalTokens.type.labelFamily,
    fontSize: huddleModalTokens.type.helperSize,
    lineHeight: huddleModalTokens.type.helperLine,
    color: huddleModalTokens.color.validationRed,
  },
  appModalSubtext: {
    fontFamily: huddleModalTokens.type.bodyFamily,
    fontSize: huddleModalTokens.type.subtextSize,
    lineHeight: huddleModalTokens.type.subtextLine,
    color: huddleModalTokens.color.text,
  },
  appModalActionRow: {
    flexDirection: "row",
    gap: huddleModalTokens.spacing.x3,
    paddingTop: huddleModalTokens.spacing.x1,
  },
  appModalPrimaryButton: {
    flex: 1,
    height: huddleModalTokens.size.buttonHeight,
    borderRadius: huddleModalTokens.radius.button,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: huddleModalTokens.color.blue,
    shadowColor: huddleModalTokens.color.blue,
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  appModalSecondaryButton: {
    flex: 1,
    height: huddleModalTokens.size.buttonHeight,
    borderRadius: huddleModalTokens.radius.button,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: huddleModalTokens.color.canvas,
    shadowColor: huddleModalTokens.color.neutralShadow,
    shadowOpacity: 0.85,
    shadowRadius: 18,
    shadowOffset: { width: 5, height: 5 },
    elevation: 2,
  },
  pressed: {
    opacity: 0.78,
  },
  disabled: {
    opacity: 0.55,
  },
});
