import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "zh-TW" | "zh-CN";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Brand
    "app.name": "huddle",
    "app.subheadline": "Pet care & social",
    
    // Navigation
    "nav.home": "Home",
    "nav.social": "Social",
    "nav.chats": "Chats",
    "nav.ai_vet": "AI Vet",
    "nav.map": "Map",
    
    // Global Header
    "header.free": "Free",
    "header.premium": "Plus",
    "header.upgrade": "Upgrade",
    
    // Home
    "home.greeting": "Hi, {name}! 👋",
    "home.subtitle": "Care for your pets",
    "home.wisdom": "huddle Wisdom",
    "home.next_event": "Next Event",
    "home.wisdom.dog.1": "Dogs need 1-2 hours of exercise daily. Consider adding an extra evening walk!",
    "home.wisdom.dog.2": "Regular brushing helps reduce shedding and keeps your dog's coat healthy.",
    "home.wisdom.dog.3": "Mental stimulation is just as important as physical exercise for dogs.",
    "home.wisdom.dog.4": "Dental health matters! Brush your dog's teeth 2-3 times per week to prevent disease.",
    "home.wisdom.cat.1": "Cats need fresh water daily. Consider a cat fountain to encourage hydration.",
    "home.wisdom.cat.2": "Provide scratching posts to keep your cat's claws healthy and save your furniture.",
    "home.wisdom.cat.3": "Cats are crepuscular - most active at dawn and dusk. Plan playtime accordingly!",
    "home.wisdom.cat.4": "Regular vet checkups are crucial - cats hide illness well until it's serious.",
    "home.wisdom.bird.1": "Birds need 10-12 hours of sleep. Cover their cage at night for quality rest.",
    "home.wisdom.bird.2": "Fresh fruits and vegetables should be part of your bird's daily diet.",
    "home.wisdom.bird.3": "Birds are social creatures and need daily interaction and mental stimulation.",
    "home.wisdom.bird.4": "Rotate toys weekly to prevent boredom and encourage natural foraging behaviors.",
    "home.wisdom.rabbit.1": "Rabbits need unlimited hay for healthy digestion and dental wear.",
    "home.wisdom.rabbit.2": "Provide a safe space for your rabbit to run and binky - they need daily exercise!",
    "home.wisdom.rabbit.3": "Regular grooming prevents hairballs, especially during shedding season.",
    "home.wisdom.rabbit.4": "Rabbits are social - consider bonding with another rabbit for companionship.",
    "home.wisdom.reptile.1": "UV lighting and proper temperatures are crucial for reptile health.",
    "home.wisdom.reptile.2": "Research your reptile's specific humidity needs - it varies greatly by species.",
    "home.wisdom.reptile.3": "Calcium and vitamin D3 supplements prevent metabolic bone disease.",
    "home.wisdom.reptile.4": "Regular fecal checks help detect parasites common in captive reptiles.",
    "home.wisdom.hamster.1": "Hamsters are nocturnal - expect nighttime wheel running and activity!",
    "home.wisdom.hamster.2": "Provide a large cage (450+ sq inches) with deep bedding for burrowing.",
    "home.wisdom.hamster.3": "Fresh vegetables in small amounts make great healthy treats.",
    "home.wisdom.hamster.4": "Syrian hamsters must live alone, but dwarf species can sometimes cohabitate.",
    "home.wisdom.other.1": "Research your pet's specific care needs - every species is unique!",
    "home.wisdom.other.2": "Find a veterinarian experienced with your type of pet.",
    "home.wisdom.other.3": "Join online communities to learn from other owners' experiences.",
    "home.wisdom.other.4": "Proper diet and habitat setup are the foundation of exotic pet care.",
    
    // Social
    "social.discovery": "Discovery",
    "social.nearby": "huddle Nearby",
    "social.nannies": "Nannies",
    "social.playdates": "Playdates",
    "social.animal_lovers": "Animal Lovers",
    "social.verified": "Verified",
    "social.star_prompt": "Buy a star pack to immediately chat with the user",
    "Buy a star pack to immediately chat with the user": "Buy a star pack to immediately chat with the user",
    "Boost sent": "Boost sent",
    "social.support": "Support",
    "social.report": "Report",
    "social.hide": "Hide",
    "social.wave": "Wave",
    "social.match": "Double Wave!",
    "social.user.marcus.name": "Marcus",
    "social.user.emma.name": "Emma",
    "social.user.james.name": "James",
    "social.location.central_park": "Central Park",
    "social.location.dog_run": "Dog Run",
    "social.location.pet_cafe": "Pet Cafe",
    "social.profile.sarah.name": "Sarah",
    "social.profile.sarah.location": "Central Park",
    "social.profile.sarah.bio": "Love hiking with Bella and meeting new friends! Available for weekend adventures.",
    "social.profile.sarah.title": "Sarah, 31 Years Old",
    "social.profile.sarah.photo_alt": "Sarah & Bella",
    "social.profile.tag.trail_hiker": "#TrailHiker",
    "social.profile.tag.dog_friendly": "#DogFriendly",
    "social.profile.nearby_bio": "Friendly and open to meeting new pet lovers nearby.",
    "social.match_message": "You and Sarah waved at each other. Start a chat to say hi!",
    "Normal Chat": "Normal Chat",
    "Broadcast Alert": "Broadcast Alert",
    
    // Dr. Huddle / AI Vet
    "ai.name": "Dr. huddle",
    "Dr. Huddle": "Dr. huddle",
    "Dr. Huddle is thinking...": "Dr. huddle is thinking...",
    "ai.online": "Online",
    "ai.analyzing": "Analyzing for",
    "ai.disclaimer": "Dr. huddle is an AI assistant for informational purposes only. Information provided can be wrong. Always seek professional veterinary opinions. Visit a clinic immediately if you have doubts or an emergency.",
    "ai.placeholder": "Type a message...",
    "ai.attach_pet": "Attach Pet Profile",
    
    // Map
    "map.search": "Find dog parks, vets, or friends...",
    "map.filter_all": "All",
    "map.filter_stray": "Stray",
    "map.filter_lost": "Lost",
    "map.filter_found": "Found",
    "map.filter_friends": "Friends",
    "map.filter_others": "Others",
    "map.go_online": "Go Online",
    "map.broadcast": "Broadcast Alert",
    "map.broadcast_remark": "Broadcasts to online users within {distance} miles; active for 48 hours.",
    "map.call_now": "Call Now",
    "map.navigate": "Navigate",
    "map.found_btn": "Found",
    "map.remove_pin": "Remove Pin?",
    "map.24h": "24h",
    "See Further": "See Further",
    "Extend search by +5km": "Extend search by +5km",
    
    // Chats
    "chats.title": "Chats",
    "chats.new_huddles": "New huddlers",
    "chats.create_group": "Create Group",
    "chats.group_name": "Group Name",
    "chats.add_members": "Add Members",
    "chats.allow_control": "Allow members to manage group",
    "chats.tab.chats": "Chats",
    "chats.tab.groups": "Groups",
    "chats.connecting": "Connecting to chat server...",
    "chats.create_group_prompt": "Create a group to start chatting!",
    "chats.verify_to_create": "Get verified to create groups",
    "No conversations found": "No conversations found",
    "No groups found": "No groups found",
    "Load more": "Load more",
    "Just now": "Just now",
    "h ago": "h ago",
    "d ago": "d ago",
    "✓ Verified": "✓ Verified",
    "Verified User": "Verified User",
    "Not Verified": "Not Verified",
    "One-time purchase": "One-time purchase",
    "Buy Now": "Buy Now",
    "Premium Tip:": "Tip:",
    "Get unlimited media uploads + more features for just $8.99/month": "Get unlimited media uploads + more features for just $8.99/month",
    "Let's Get Started": "Get Started",
    "Welcome to huddle": "Welcome to huddle",
    "Family mesh for pets": "Family mesh for pets",
    "Please upload a valid ID or passport": "Please upload a valid ID or passport",
    "PNG, JPG, PDF up to 10MB": "PNG, JPG, PDF up to 10MB",
    "auth.errors.session_expired": "Session expired. Please sign in again.",
    "Please fill in your legal name and phone number first": "Please fill in your legal name and phone number first",
    "has been added to your huddle! 🎉": "has been added to your huddle! 🎉",
    
    // Settings
    "settings.title": "Settings",
    "settings.account_settings": "Account Settings",
    "Account Settings": "Account Settings",
    "settings.profile": "Profile",
    "settings.account_security": "Account & Security",
    "settings.personal_info": "Personal Info",
    "settings.password": "Password",
    "settings.biometric": "Biometric Login",
    "settings.2fa": "Two-Factor Auth",
    "settings.privacy": "Privacy",
    "settings.private_account": "Private Account",
    "settings.map_visibility": "Map Visibility",
    "settings.trusted_locations": "Trusted Locations",
    "settings.notifications": "Notifications",
    "settings.pause_all": "Pause All",
    "settings.social_notif": "Social (Waves/Matches)",
    "settings.safety_notif": "Safety (Alerts)",
    "settings.ai_notif": "Dr. huddle",
    "settings.email_notif": "Email Notifications",
    "settings.language": "Language",
    "settings.help_support": "Help & Support",
    "settings.report_bug": "Report a Bug",
    "settings.privacy_policy": "Privacy Policy",
    "settings.terms": "Terms of Service",
    "family.upsell_title": "Family invites are Gold-only",
    "family.upsell_body": "Upgrade to Gold to unlock family invites and shared access.",
    "family.upsell_cta": "Upgrade to Gold",
    "settings.deactivate": "Deactivate Account",
    "Verification Rejected": "Verification Rejected",
    "Review Note": "Review Note",
    "settings.delete": "Delete Account",
    "settings.logout": "Logout",
    "settings.pending": "Identity pending",
    "settings.verified_badge": "Verified huddler",
    
    // Profile
    "profile.edit": "Edit Profile",
    "profile.display_name": "Display Name",
    "profile.bio": "Bio",
    "profile.gender": "Gender",
    "profile.genre": "Genre/Orientation",
    "profile.dob": "Date of Birth",
    "profile.height": "Height",
    "profile.degree": "Highest Degree",
    "profile.occupation": "Occupation",
    "profile.school": "School",
    "profile.major": "Major",
    "profile.affiliation": "Affiliation",
    "profile.has_car": "Own a Car?",
    "profile.owns_pets": "Currently own pets?",
    "profile.show": "Show",
    
    // Onboarding Profile Setup
    "Display Name": "Display Name",
    "How should others call you?": "How should others call you?",
    "Phone (Optional)": "Phone (Optional)",
    "+1 234 567 8900": "+1 234 567 8900",
    "Bio": "Bio",
    "Tell us about yourself...": "Tell us about yourself...",
    "Demographics": "Demographics",
    "Gender": "Gender",
    "Sexual Orientation": "Sexual Orientation",
    "Orientation": "Orientation",
    "Date of Birth": "Date of Birth",
    "Age": "Age",
    "Location": "Location",
    "Your city": "Your city",
    "Pet Experience": "Pet Experience",
    "Years of experience": "Years of experience",
    "Pet Driver": "Pet Driver",
    "I have a car and can transport pets": "I have a car and can transport pets",
    "Languages": "Languages",
    "Social Level Boosters": "Social Level Boosters",
    "Height (cm)": "Height (cm)",
    "Height": "Height",
    "Your height in cm": "Your height in cm",
    "kg": "kg",
    "lbs": "lbs",
    "Relationship Status": "Relationship Status",
    "Select...": "Select...",
    "Academic & Skills": "Academic & Skills",
    "Academic": "Academic",
    "Select degree...": "Select degree...",
    "School Name": "School Name",
    "Major": "Major",
    "Occupation": "Occupation",
    "Job title / Occupation": "Job title / Occupation",
    "Affiliation": "Affiliation",
    "Local shelters, clubs, organizations...": "Local shelters, clubs, organizations...",
    "Currently own any pets?": "Currently own any pets?",
    "You can add pet profiles later": "You can add pet profiles later",
    "Social Availability": "Social Availability",
    "Are you open to connecting?": "Are you open to connecting?",
    "I identify as:": "I identify as:",
    "Continue to Pet Setup": "Continue to Pet Setup",
    "Complete Setup": "Complete Setup",
    "Male": "Male",
    "Female": "Female",
    "Non-binary": "Non-binary",
    "PNA": "PNA",
    "Straight": "Straight",
    "Gay/Lesbian": "Gay/Lesbian",
    "Bisexual": "Bisexual",
    "Queer": "Queer",
    "College": "College",
    "Associate Degree": "Associate Degree",
    "Bachelor": "Bachelor",
    "Master": "Master",
    "Doctorate / PhD": "Doctorate / PhD",
    "Single": "Single",
    "In a relationship": "In a relationship",
    "Open relationship": "Open relationship",
    "Married": "Married",
    "Divorced": "Divorced",
    "Dogs": "Dogs",
    "Cats": "Cats",
    "Birds": "Birds",
    "Fish": "Fish",
    "Reptiles": "Reptiles",
    "Small Mammals": "Small Mammals",
    "Horses": "Horses",
    "Exotic Pets": "Exotic Pets",
    "Farm Animals": "Farm Animals",
    "None": "None",
    "Pet Parents": "Pet Parents",
    "Pet Nanny": "Pet Nanny",
    "Animal Friend (no pet)": "Animal Friend (no pet)",
    "English": "English",
    "Cantonese": "Cantonese",
    "Mandarin": "Mandarin",
    "Spanish": "Spanish",
    "French": "French",
    "Japanese": "Japanese",
    "Korean": "Korean",
    "German": "German",
    "Portuguese": "Portuguese",
    "Italian": "Italian",
    
    // Pet Profile
    "pet.title": "Pet Profile",
    "pet.basics": "Basics",
    "pet.vault": "The Vault",
    "pet.lifestyle": "Lifestyle",
    "pet.name": "Name",
    "pet.species": "Species",
    "pet.breed": "Breed",
    "pet.gender": "Gender",
    "pet.weight": "Weight",
    "pet.dob": "Date of Birth",
    "pet.vaccinations": "Vaccinations",
    "pet.medications": "Medications",
    "pet.microchip": "Microchip ID",
    "pet.vet_contact": "Vet Contact",
    "pet.temperament": "Temperament",
    "pet.routine": "Routine",
    
    // Premium
    "premium.title": "huddle Plus",
    "Huddle Premium": "huddle Plus",
    "premium.unlock": "See everything Plus includes",
    "premium.upgrade": "See what's included",
    "premium.maybe_later": "Maybe later",
    "premium.compare": "Compare Plans",
    "premium.free_plan": "Free",
    "premium.premium_plan": "Premium",
    "premium.grey_badge": "Grey Badge",
    "premium.gold_badge": "Gold Badge",
    "premium.text_ai": "Text AI",
    "premium.photo_audio_ai": "Photo/Audio AI",
    "premium.alert_1mi": "1-mile Alert",
    "premium.alert_5mi": "5-mile Alert",
    "premium.single_filter": "Single Filter",
    "premium.multi_filter": "Multi-select Filters",
    "premium.ghost_mode": "Ghost Mode",
    "premium.featured": "Featured Posting",
    

    // Nanny Booking Modal
    "booking.title": "Book Nanny",
    "booking.pet_nanny": "Pet Nanny",
    "booking.service_date": "Service Date",
    "booking.start_time": "Start Time",
    "booking.end_time": "End Time",
    "booking.which_pet": "Which Pet?",
    "booking.select_pet": "Select a pet…",
    "booking.location": "Service Location",
    "booking.location_not_set": "Set location in your profile",
    "booking.amount": "Booking Amount (USD)",
    "booking.amount_note": "Minimum $10 · Payment held in escrow until service completed",
    "booking.amount_calculated": "Price is calculated from sitter hourly rate",
    "booking.cancel": "Cancel",
    "booking.pay": "Pay via Stripe",
    "booking.payment_failed": "Failed to initiate booking payment",
    // Common
    "common.save": "Save",
    "Save": "Save",
    "Legal name is required": "Legal name is required",
    "Display name is required": "Display name is required",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.delete": "Delete",
    "common.create": "Create",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.others": "Others",
    "✓": "✓",
    "$9.99": "$9.99",
    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.remember": "Remember Me",
    "auth.create_account": "Create Account",
    "auth.use_phone": "Use phone number instead",
    "auth.use_email": "Use email instead",
    "auth.apple": "Apple",
    "auth.google": "Google",
    "auth.soon": "Soon",
    "auth.or_continue": "Or continue with",
    "auth.forgot_password": "Forgot Password?",
    "auth.reset_enter_email": "Enter your email address to reset password",
    "auth.reset_failed": "Failed to send reset email",
    "auth.reset_sent": "Reset link sent to your email!",
    "auth.by_continuing": "By continuing, you agree to our",
    "auth.terms": "Terms of Service",
    "auth.and": "and",
    "auth.privacy": "Privacy Policy",
    "auth.welcome_back": "Good to see you",
    "auth.use_email_signup": "Please use an email address to sign up",
    "auth.account_created": "Account created. Set up your profile.",
    "Welcome to Huddle! 🎉": "Welcome to huddle! 🎉",
    "Welcome to Huddle! You can add pets later.": "Welcome to huddle! You can add pets later.",
    "auth.errors.invalid_email": "Please enter a valid email address",
    "auth.errors.invalid_phone": "Please enter a valid phone number",
    "auth.errors.password_min": "Password must be at least 8 characters",
    "auth.errors.password_upper": "Password must contain at least 1 uppercase letter",
    "auth.errors.password_number": "Password must contain at least 1 number",
    "auth.errors.password_special": "Password must contain at least 1 special character",
    "auth.errors.invalid_identifier": "Please enter a valid email or phone number",
    "auth.errors.invalid": "Invalid email/phone or password",
    "auth.errors.account_exists": "An account with this email already exists",
    "auth.errors.display_name_required": "Display name is required",
    "auth.errors.legal_name_required": "Legal name is required",
    "error.missing_fields": "Please complete all required fields",
    "auth.password_strength.length": "✓ At least 8 characters",
    "auth.password_strength.upper": "✓ One uppercase letter",
    "auth.password_strength.number": "✓ One number",
    "auth.password_strength.special": "✓ One special character",
    // Social
    "You and Sarah waved at each other. Start a chat to say hi!": "You and Sarah waved at each other. Start a chat to say hi!",
    "Start Chat": "Start Chat",
    "Chat media": "Chat media",
    // Settings & Identity
    "Invite link copied": "Invite link copied",
    "Failed to copy invite link": "Failed to copy invite link",
    "Share this link to invite a family member to your huddle.": "Share this link to invite a family member to your huddle.",
    "Copy Invite Link": "Copy Invite Link",
    "Verified": "Verified",
    "Verified Huddler": "Verified huddler",
    "Upload a government-issued ID or passport for review. Approval typically takes 24-48 hours.": "Upload a government-issued ID or passport for review. Approval typically takes 24-48 hours.",
    "Click to upload ID/Passport": "Click to upload ID/Passport",
    "Submit": "Submit",
    "Update": "Update",
    "Verify": "Verify",
    "First, verify your current password": "First, verify your current password",
    "Place your finger on the sensor": "Place your finger on the sensor",
    "Scanning...": "Scanning...",
    "Success!": "Success!",
    "Touch the fingerprint sensor": "Touch the fingerprint sensor",
    "Keep your finger steady": "Keep your finger steady",
    "Biometric authentication enabled": "Biometric authentication enabled",
    "This action cannot be undone. All your data will be permanently deleted.": "This action cannot be undone. All your data will be permanently deleted.",
    "Verify your identity to unlock full community features": "Verify your identity to unlock full community features",
    "This is kept private and used only for verification": "This is kept private and used only for verification",
    "Submit your ID for review to earn a verified badge": "Submit your ID for review to earn a verified badge",
    "Start Verification": "Start Verification",
    "Submitting for Review...": "Submitting for Review...",
    "Processing your verification request": "Processing your verification request",
    "Verification Submitted": "Verification Submitted",
    "Your verification is pending approval": "Your verification is pending approval",
    "Skipping verification may affect your user journey": "Skipping verification may affect your user journey",
    "Unverified users have limited access to certain community features and may appear less trustworthy to others.": "Unverified users have limited access to certain community features and may appear less trustworthy to others.",
    "Yes, Skip Verification": "Yes, Skip Verification",
    "Skip for now": "Skip for now",
    "Continue to Profile Setup": "Continue to Profile Setup",
    "Verification submitted for review": "Verification submitted for review",
    // Hazard Scanner
    "Upload a photo of any object your pet found. AI will identify if it's toxic or safe.": "Upload a photo of any object your pet found. AI will identify if it's toxic or safe.",
    "Preview": "Preview",
    "Change Photo": "Change Photo",
    "Scan for Hazards": "Scan for Hazards",
    "identified as": "identified as",
    "Scan Another Item": "Scan Another Item",
    "Call Emergency Vet Now": "Call Emergency Vet Now",
    "appears to be safe": "appears to be safe",
    // Profile & Pets
    "Legal Name": "Legal Name",
    "Your legal name": "Your legal name",
    "Your display name": "Your display name",
    "Phone (+XXX)": "Phone (+XXX)",
    "Select breed": "Select breed",
    "Siamese": "Siamese",
    "Persian": "Persian",
    "Maine Coon": "Maine Coon",
    "Ragdoll": "Ragdoll",
    "Bengal": "Bengal",
    "British Shorthair": "British Shorthair",
    "Sphynx": "Sphynx",
    "Scottish Fold": "Scottish Fold",
    "Abyssinian": "Abyssinian",
    "Phone number is required": "Phone number is required",
    "Date of birth is required": "Date of birth is required",
    "Save Pet Profile": "Save Pet Profile",
    "Friend": "Friend",
    "Weight": "Weight",
    "months": "months",
    "year": "year",
    "years": "years",
    // Premium
    "You're a Gold Member!": "You're a Gold Member!",
    "You're a Premium Member!": "You're on Plus.",
    "Status:": "Status:",
    "active": "active",
    "Manage": "Manage",
    "Processing...": "Processing...",
    "Upgrade to": "Upgrade to",
    "Buy": "Buy",
    "Secure payments powered by Stripe": "Secure payments powered by Stripe",
    // Premium Feature Table
    "Badge Type": "Badge Type",
    "Grey": "Grey",
    "Blue Premium": "Blue Premium",
    "Gold Crown": "Gold Crown",
    "Chat Access": "Chat Access",
    "Limited": "Limited",
    "Unlimited": "Unlimited",
    "Unlimited + Priority": "Unlimited + Priority",
    "AI Vet": "AI Vet",
    "Text Only": "Text Only",
    "Photo + Audio": "Photo + Audio",
    "Unlimited Media": "Unlimited Media",
    "Broadcast Range": "Broadcast Range",
    "1 mile": "1 mile",
    "5 miles": "5 miles",
    "10 miles": "10 miles",
    "Social Filters": "Social Filters",
    "Basic": "Basic",
    "Advanced": "Advanced",
    "Advanced + Boosts": "Advanced + Boosts",
    "Ghost Mode": "Ghost Mode",
    "Notice Board": "Threads",
    "Priority Support": "Priority Support",
    "Marketplace Priority": "Marketplace Priority",
    "Ad-free Experience": "Ad-free Experience",
    // Add-ons
    "3 Star Pack": "3 Star Pack",
    "Boost your profile visibility": "Boost your profile visibility",
    "Emergency Mesh Alert": "Emergency Mesh Alert",
    "Lost pet emergency broadcast": "Lost pet emergency broadcast",
    "10 AI Vet Media Credits": "10 AI Vet Media Credits",
    "Upload photos/videos to AI Vet": "Upload photos/videos to AI Vet",
    "Family Member Slot": "Family Member Slot",
    "Add 1 family member to account": "Add 1 family member to account",
    "Verified Badge": "Verified Badge",
    "One-time ID verification": "One-time ID verification",
    // Pet Wizard / Pet Details
    "Step": "Step",
    "Keep track of important health info": "Keep track of important health info",
    "Microchip ID (15 digits)": "Microchip ID (15 digits)",
    "digits": "digits",
    "About": "About",
    "Next Reminder": "Next Reminder",
    "Help others understand your pet": "Help others understand your pet",
    "Confirm": "Confirm",
    "'s details": "'s details",
    "recorded": "recorded",
    "Back": "Back",
    "Continue": "Continue",
    "Pet": "Pet",
    // Premium Footer
    "Notice Board is Premium only": "Threads are Plus only",
    "Upgrade to post notices, share updates, and connect with your huddle community.": "Upgrade to post notices, share updates, and connect with your huddle community.",
    "Extended Broadcast needs Premium": "Extended Broadcast needs Plus",
    "Free users broadcast within 1 km. Upgrade for up to 5 km mesh alerts.": "Free users broadcast within 1 km. Upgrade for up to 5 km mesh alerts.",
    "Media sharing is a Premium perk": "Media sharing is a Plus feature",
    "Send photos & files in chats. Unlock unlimited media with Premium.": "Send photos & files in chats. Available on Plus.",
    "Alert limit reached": "Alert limit reached",
    "Free users get 2 mesh alerts per day. Upgrade for unlimited emergency broadcasts.": "Free users get 2 mesh alerts per day. Upgrade for unlimited emergency broadcasts.",
    "Unlock the full huddle experience": "Everything you need for your pet",
    "Premium gives you access to all features — starting at just $8.99/month.": "Plus gives you access to all features — starting at $8.99/month.",
    "Verified Status": "Verified Status",
    "5 km Broadcast Radius": "5 km Broadcast Radius",
    "Notice Board Access": "Threads Access",
    "Chat Image Access": "Chat Image Access",
    "Priority Visibility": "Priority Visibility",
    "Ad-Free Experience": "Ad-Free Experience",
    "huddle Premium": "huddle Plus",
    "Welcome to huddle Premium!": "You're on huddle Plus.",
    "Upgrade Now": "Upgrade Now",
    "Maybe Later": "Maybe Later",
    // AI Vet Greeting
    "Hello there! I'm Dr. Huddle, your friendly AI pet assistant. 🐾": "Hello there! I'm Dr. huddle, your friendly AI pet assistant. 🐾",
    "I see you've selected": "I see you've selected",
    "your": "your",
    "old": "old",
    "I'm here to help with any questions about": "I'm here to help with any questions about",
    "'s health and wellness.": "'s health and wellness.",
    "While I can provide helpful information and guidance, remember that I'm always happy to point you toward your local vet for hands-on care.": "While I can provide helpful information and guidance, remember that I'm always happy to point you toward your local vet for hands-on care.",
    "What can I help you with today?": "What can I help you with today?",
    // Language & Misc
    "language.english": "English",
    "language.zh_tw": "繁體中文",
    "language.zh_cn": "简体中文",
    "invite.slots_available": "Invite slots available: {count}",
    "invite.no_slots": "No invite slots available",
    "Upload & Submit": "Upload & Submit",
    "Invite": "Invite",
    "Family": "Family",
    "Invite Family Member": "Invite Family Member",
    "Change Password": "Change Password",
    "Current password": "Current password",
    "New password (min 8 characters)": "New password (min 8 characters)",
    "Confirm new password": "Confirm new password",
    "Enter your new password": "Enter your new password",
    "Biometric Setup": "Biometric Setup",
    "Your ID is under review": "Your ID is under review",
    "Upload failed": "Upload failed",
    "ID uploaded! Waiting for approval": "ID uploaded! Waiting for approval",
    "v1.0.0 (2026)": "v1.0.0 (2026)",
    "User": "User",
    "Gold": "Gold",
    "Premium": "Plus",
    "Free": "Free",
    "Manage Subscription": "Manage Subscription",
    "Non-Social": "Non-Social",
    "Hide from social discovery": "Hide from social discovery",
    "Hide from Map": "Hide from Map",
    "Don't show my location": "Don't show my location",
    "Account deletion requested. You will receive a confirmation email.": "Account deletion requested. You will receive a confirmation email.",
    "Please describe the bug": "Please describe the bug",
    "Bug report submitted. Thank you!": "Bug report submitted. Thank you!",
    "Current password is incorrect": "Current password is incorrect",
    "Password verified": "Password verified",
    "Failed to verify password": "Failed to verify password",
    "Password must be at least 8 characters": "Password must be at least 8 characters",
    "Passwords do not match": "Passwords do not match",
    "Password updated successfully": "Password updated successfully",
    "Failed to update password": "Failed to update password",
    "To deactivate, contact support@huddle.app": "To deactivate, contact support@huddle.app",
    "Identity Verification": "Identity Verification",
    "Waiting for Approval": "Waiting for Approval",
    "Upload ID/Passport": "Upload ID/Passport",
    // Map Extensions
    "map.distance_km": "{count} km",
    "map.distance_km_max": "{count} km (max)",
    "map.word_count": "{count}/{max} words",
    "map.add_photo": "Add photo",
    "map.broadcast_alert": "Broadcast {type} Alert",
    "map.supports": "{count} supports",
    "map.vet_clinic": "Veterinary Clinic",
    "map.vet.hk_clinic": "Hong Kong Veterinary Clinic",
    "map.vet.central_hospital": "Central Pet Hospital",
    "map.vet.wan_chai": "Wan Chai Animal Care",
    "map.vet.kowloon": "Kowloon Vet Centre",
    "map.create_alert_failed": "Failed to create alert",
    "Location accuracy too low. Please retry with better GPS signal.": "Location accuracy too low. Please retry with better GPS signal.",
    "Phone number not available": "Phone number not available",
    "Please select a location on the map": "Please select a location on the map",
    "Alert broadcasted!": "Alert broadcasted!",
    "Please login to support alerts": "Please login to support alerts",
    "You've already supported this alert": "You've already supported this alert",
    "Failed to support alert": "Failed to support alert",
    "Please login to report alerts": "Please login to report alerts",
    "Alert reported": "Alert reported",
    "You've already reported this alert": "You've already reported this alert",
    "Failed to report alert": "Failed to report alert",
    "Alert hidden": "Alert hidden",
    "You won't see posts from this user": "You won't see posts from this user",
    "Tap map to select location": "Tap map to select location",
    "Brief description (max 20 words)...": "Brief description (max 20 words)...",
    // Notice Board
    "notice.category.social": "Social",
    "notice.category.charity": "Charity",
    "notice.category.news": "News",
    "notice.dummy_content": "Just adopted this adorable tabby! 🐱 Looking for other cat parents in the area to share tips and maybe arrange some playdates. She's 2 years old and loves to cuddle!",
    "notice.dummy_author": "Cat Lover",
    "Post": "Post",
    "Unlock": "Unlock",
    "No notices yet": "No notices yet",
    "Post Notice": "Post Notice",
    "Create Notice": "Create Notice",
    "What's on your mind?": "What's on your mind?",
    "Notice posted!": "Notice posted!",
    "Failed to post notice": "Failed to post notice",
    "Support removed": "Support removed",
    "Notice reported - our team will review it": "Notice reported - our team will review it",
    "Notice hidden": "Notice hidden",
    "Support": "Support",
    "Report": "Report",
    "Hide": "Hide",
    "Block User": "Block User",
    "Please enter some content": "Please enter some content",
    // Filters
    "Filters": "Filters",
    "Basic Filters": "Basic Filters",
    "Looking for": "Looking for",
    "Distance": "Distance",
    "Extend search beyond 150km": "Extend search beyond 150km",
    "Age Range": "Age Range",
    "Pet Height": "Pet Height",
    "Premium Filters": "Plus Filters",
    "PRO": "PRO",
    "Verified Only": "Verified Only",
    "ID-checked users only": "ID-checked users only",
    "Active Now": "Active Now",
    "Seen in last 24 hours": "Seen in last 24 hours",
    "Pet Temperament Match": "Pet Temperament Match",
    "Filter by personality sync": "Filter by personality sync",
    "Logistics & Skills": "Logistics & Skills",
    "Has a Car": "Has a Car",
    "Pet School Graduates": "Pet School Graduates",
    "Common Huddle Friends": "Common huddle friends",
    "Your Huddle is Empty": "Your huddle is empty",
    "has been added to your huddle!": "has been added to your huddle!",
    "Show mutual connections": "Show mutual connections",
    "Apply Filters": "Apply Filters",
    "Any": "Any",
    "Small": "Small",
    "Medium": "Medium",
    "Large": "Large",
    "Extra Large": "Extra Large",
    // Social Demo
    "Sarah & Bella": "Sarah & Bella",
    "Sarah, 31 Years Old": "Sarah, 31 Years Old",
    "#TrailHiker": "#TrailHiker",
    "#DogFriendly": "#DogFriendly",
    "Love hiking with Bella and meeting new friends! Available for weekend adventures.": "Love hiking with Bella and meeting new friends! Available for weekend adventures.",
    "Friendly and open to meeting new pet lovers nearby.": "Friendly and open to meeting new pet lovers nearby.",
    "Marcus": "Marcus",
    "Emma": "Emma",
    "James": "James",
    "Central Park": "Central Park",
    "Dog Run": "Dog Run",
    "Pet Cafe": "Pet Cafe",
    // AI Vet Limits
    "ai.errors.free_limit": "You've reached your free message limit for this month",
    "ai.fallback_message": "I appreciate your question! Based on what you've described, I'd suggest keeping a close eye on your pet over the next day or two. Monitor for any changes in appetite, energy levels, or the symptoms you mentioned.\n\nIf things don't improve within 48 hours, or if you notice anything concerning, I'd definitely recommend visiting your local vet for a proper check-up. They'll be able to give your pet a hands-on examination.\n\nIn the meantime, I'm here if you have any more questions! 🐕",
    "ai.free_remaining": "{count} free conversations remaining this month",
    "ai.free_exhausted": "Free conversations exhausted",
    // Hazard Scanner
    "hazard.image_optimized": "Image optimized (saved {savedKB} KB)",
    "hazard.rate_limit": "Scan limit reached. Free includes 3 scans per day.",
    // Premium misc
    "premium.savings_26": "Save 26%",
    "premium.savings_25": "Save 25%",
    "per_month_short": "{value}/month",
    // Home
    "home.next_event_sample": "Mid-day Walk, 12:00 PM",
  },
  "zh-TW": {
    // Brand
    "app.name": "huddle",
    "app.subheadline": "寵物照護與社交",
    
    // Navigation
    "nav.home": "首頁",
    "nav.social": "社交",
    "nav.chats": "聊天",
    "nav.ai_vet": "AI 獸醫",
    "nav.map": "地圖",
    
    // Global Header
    "header.free": "免費版",
    "header.premium": "星級會員",
    "header.upgrade": "升級",
    
    // Home
    "home.greeting": "嗨，{name}！👋",
    "home.subtitle": "一起照顧你的毛孩",
    "home.wisdom": "毛孩百科",
    "home.next_event": "下一個活動",
    "home.wisdom.dog.1": "狗狗每天需要 1-2 小時運動，考慮增加晚間散步！",
    "home.wisdom.dog.2": "定期梳毛可減少掉毛並保持毛髮健康。",
    "home.wisdom.dog.3": "心理刺激與身體運動同樣重要。",
    "home.wisdom.dog.4": "牙齒保健很重要！每週刷牙 2-3 次可預防疾病。",
    "home.wisdom.cat.1": "貓咪每天需要新鮮飲水，貓飲水機可促進飲水。",
    "home.wisdom.cat.2": "提供抓抓柱能保護家具並維持爪子健康。",
    "home.wisdom.cat.3": "貓咪在清晨與黃昏較活躍，可安排遊戲時間。",
    "home.wisdom.cat.4": "定期健檢很重要，貓咪常會隱藏病痛。",
    "home.wisdom.bird.1": "鳥類需要 10-12 小時睡眠，夜間可覆蓋籠子。",
    "home.wisdom.bird.2": "每日攝取新鮮蔬果有助於營養均衡。",
    "home.wisdom.bird.3": "鳥類需要每日互動與心智刺激。",
    "home.wisdom.bird.4": "每週更換玩具可避免無聊並鼓勵覓食行為。",
    "home.wisdom.rabbit.1": "兔子需要無限量牧草以維持消化與牙齒健康。",
    "home.wisdom.rabbit.2": "提供安全空間讓兔子奔跑與跳躍，需每日運動。",
    "home.wisdom.rabbit.3": "定期梳毛可避免毛球，換毛期更重要。",
    "home.wisdom.rabbit.4": "兔子是社交動物，可考慮結伴飼養。",
    "home.wisdom.reptile.1": "爬蟲需要 UV 燈與適當溫度。",
    "home.wisdom.reptile.2": "不同物種濕度需求不同，請做足研究。",
    "home.wisdom.reptile.3": "鈣與維生素 D3 補充可預防代謝性骨病。",
    "home.wisdom.reptile.4": "定期糞檢有助於發現寄生蟲。",
    "home.wisdom.hamster.1": "倉鼠夜行性，夜間活動與跑輪很常見。",
    "home.wisdom.hamster.2": "提供大籠舍與深墊材以利挖掘。",
    "home.wisdom.hamster.3": "少量新鮮蔬菜是健康零食。",
    "home.wisdom.hamster.4": "黃金鼠需單獨飼養，部分侏儒鼠可同居。",
    "home.wisdom.other.1": "每種動物需求不同，請研究其照護方式。",
    "home.wisdom.other.2": "尋找有相關經驗的獸醫。",
    "home.wisdom.other.3": "加入社群與其他飼主交流經驗。",
    "home.wisdom.other.4": "良好飲食與棲地是照護基礎。",
    "Your Huddle is Empty": "你的 huddle 還是空的",
    "has been added to your huddle!": "已新增到你的 huddle！",
    
    // Social
    "social.discovery": "探索",
    "social.nearby": "附近的Huddler",
    "social.nannies": "暖心保姆",
    "social.playdates": "毛孩聚會",
    "social.animal_lovers": "動物之友",
    "social.verified": "已認證",
    "social.star_prompt": "購買星星包即可立即與該用戶聊天",
    "Buy a star pack to immediately chat with the user": "購買星星包即可立即與該用戶聊天",
    "Boost sent": "加速已送出",
    "social.support": "支持",
    "social.report": "檢舉",
    "social.hide": "隱藏",
    "social.wave": "打招呼",
    "social.match": "雙向打招呼！",
    "social.user.marcus.name": "Marcus",
    "social.user.emma.name": "Emma",
    "social.user.james.name": "James",
    "social.location.central_park": "中央公園",
    "social.location.dog_run": "狗狗跑區",
    "social.location.pet_cafe": "寵物咖啡館",
    "social.profile.sarah.name": "Sarah",
    "social.profile.sarah.location": "中央公園",
    "social.profile.sarah.bio": "喜歡和 Bella 一起健行、認識新朋友！週末有空一起冒險。",
    "social.profile.sarah.title": "Sarah，31 歲",
    "social.profile.sarah.photo_alt": "Sarah 與 Bella",
    "social.profile.tag.trail_hiker": "#TrailHiker",
    "social.profile.tag.dog_friendly": "#DogFriendly",
    "social.profile.nearby_bio": "友善並樂於認識附近的毛孩愛好者。",
    "social.match_message": "你和 Sarah 互相打招呼了，開始聊天吧！",
    "Normal Chat": "一般聊天",
    "Broadcast Alert": "廣播警報",
    "You and Sarah waved at each other. Start a chat to say hi!": "你和 Sarah 互相打招呼了，開始聊天吧！",
    "Start Chat": "開始聊天",
    "Chat media": "聊天媒體",
    "Sarah & Bella": "Sarah 與 Bella",
    "Sarah, 31 Years Old": "Sarah，31 歲",
    "#TrailHiker": "#TrailHiker",
    "#DogFriendly": "#DogFriendly",
    "Love hiking with Bella and meeting new friends! Available for weekend adventures.": "喜歡和 Bella 一起健行、認識新朋友！週末有空一起冒險。",
    "Friendly and open to meeting new pet lovers nearby.": "友善並樂於認識附近的毛孩愛好者。",
    "Marcus": "Marcus",
    "Emma": "Emma",
    "James": "James",
    "Central Park": "中央公園",
    "Dog Run": "狗狗跑區",
    "Pet Cafe": "寵物咖啡館",
    "Let's Get Started": "開始吧",
    "Welcome to huddle": "歡迎加入 huddle",
    "Family mesh for pets": "毛孩家庭網",
    "Please upload a valid ID or passport": "請上傳有效的身分證或護照",
    "PNG, JPG, PDF up to 10MB": "PNG、JPG、PDF 最多 10MB",
    "auth.errors.session_expired": "工作階段已過期，請重新登入。",
    "Please fill in your legal name and phone number first": "請先填寫法定姓名與電話號碼",
    "has been added to your huddle! 🎉": "已新增到你的 huddle！🎉",
    
    // Dr. Huddle / AI Vet
    "ai.name": "huddle AI 醫生",
    "Dr. Huddle": "Dr. huddle",
    "Dr. Huddle is thinking...": "Dr. huddle 正在思考...",
    "ai.online": "線上",
    "ai.analyzing": "正在分析",
    "ai.disclaimer": "huddle AI 醫生是僅供參考的人工智慧助手。提供的資訊可能有誤。請務必尋求專業獸醫意見。如有疑慮或緊急情況，請立即前往診所。",
    "ai.placeholder": "輸入訊息...",
    "ai.attach_pet": "附加寵物資料",
    
    // Map
    "map.search": "搜尋狗公園、獸醫或朋友...",
    "map.filter_all": "全部",
    "map.filter_stray": "流浪動物",
    "map.filter_lost": "走失寵物",
    "map.filter_found": "已找到",
    "map.filter_friends": "朋友",
    "map.filter_others": "其他",
    "map.go_online": "上線",
    "map.broadcast": "緊急通報",
    "map.broadcast_remark": "通報將發送給{distance}英里內的線上用戶；有效期48小時。",
    "map.call_now": "立即撥打",
    "map.navigate": "導航",
    "map.found_btn": "已找到",
    "map.remove_pin": "移除標記？",
    "map.24h": "24小時",
    "See Further": "看更遠",
    "Extend search by +5km": "搜尋距離增加 +5 公里",
    
    // Chats
    "chats.title": "聊天",
    "chats.new_huddles": "新朋友",
    "chats.create_group": "建立群組",
    "chats.group_name": "群組名稱",
    "chats.add_members": "新增成員",
    "chats.allow_control": "允許成員管理群組",
    "chats.tab.chats": "聊天",
    "chats.tab.groups": "群組",
    "chats.connecting": "正在連線至聊天伺服器...",
    "chats.create_group_prompt": "建立群組開始聊天！",
    "chats.verify_to_create": "完成認證後才能建立群組",
    "No conversations found": "找不到對話",
    "No groups found": "找不到群組",
    "Load more": "載入更多",
    "Just now": "剛剛",
    "h ago": "小時前",
    "d ago": "天前",
    "✓ Verified": "✓ 已認證",
    "Verified User": "已驗證用戶",
    "Not Verified": "未驗證",
    "One-time purchase": "一次性購買",
    "Buy Now": "立即購買",
    "Premium Tip:": "Premium 提示：",
    "Get unlimited media uploads + more features for just $8.99/month": "每月只要 $8.99 即可享有無限媒體上傳與更多功能",
    "Has a Car": "有車",
    
    // Settings
    "settings.title": "設定",
    "settings.account_settings": "帳戶設定",
    "Account Settings": "帳號設定",
    "settings.profile": "個人資料",
    "settings.account_security": "帳號與安全",
    "settings.personal_info": "個人資訊",
    "settings.password": "密碼",
    "settings.biometric": "生物辨識登入",
    "settings.2fa": "雙重驗證",
    "settings.privacy": "隱私",
    "settings.private_account": "私人帳號",
    "settings.map_visibility": "地圖可見度",
    "settings.trusted_locations": "信任的位置",
    "settings.notifications": "通知",
    "settings.pause_all": "暫停所有通知",
    "settings.social_notif": "社交（打招呼/配對）",
    "settings.safety_notif": "安全（警報）",
    "settings.ai_notif": "huddle AI 醫生",
    "settings.email_notif": "電子郵件通知",
    "settings.language": "語言",
    "settings.help_support": "說明與支援",
    "settings.report_bug": "回報問題",
    "settings.privacy_policy": "隱私權政策",
    "settings.terms": "服務條款",
    "family.upsell_title": "家庭邀請僅限 Gold",
    "family.upsell_body": "升級至 Gold 以開啟家庭邀請與共享存取。",
    "family.upsell_cta": "升級至 Gold",
    "settings.deactivate": "停用帳號",
    "Verification Rejected": "驗證被拒",
    "Review Note": "審核備註",
    "settings.delete": "刪除帳號",
    "settings.logout": "登出",
    "settings.pending": "身份驗證中",
    "settings.verified_badge": "認證huddler",
    
    // Profile
    "profile.edit": "編輯個人資料",
    "profile.display_name": "顯示名稱",
    "profile.bio": "簡介",
    "profile.gender": "性別",
    "profile.genre": "性向",
    "profile.dob": "出生日期",
    "profile.height": "身高",
    "profile.degree": "最高學歷",
    "profile.occupation": "職業",
    "profile.school": "學校",
    "profile.major": "主修",
    "profile.affiliation": "隸屬組織",
    "profile.has_car": "有車？",
    "profile.owns_pets": "目前有養寵物？",
    "profile.show": "顯示",
    
    // Onboarding Profile Setup
    "Display Name": "顯示名稱",
    "How should others call you?": "希望別人怎麼稱呼你？",
    "Phone (Optional)": "電話（選填）",
    "+1 234 567 8900": "+1 234 567 8900",
    "Bio": "簡介",
    "Tell us about yourself...": "介紹一下你自己...",
    "Demographics": "基本資料",
    "Gender": "性別",
    "Sexual Orientation": "性向",
    "Orientation": "性向",
    "Date of Birth": "出生日期",
    "Age": "年齡",
    "Location": "地點",
    "Your city": "你的城市",
    "Pet Experience": "寵物經驗",
    "Years of experience": "經驗年數",
    "Pet Driver": "寵物載運",
    "I have a car and can transport pets": "我有車可載運寵物",
    "Languages": "語言",
    "Social Level Boosters": "社交加成",
    "Height (cm)": "身高（公分）",
    "Height": "身高",
    "Your height in cm": "你的身高（公分）",
    "kg": "公斤",
    "lbs": "磅",
    "Relationship Status": "感情狀態",
    "Select...": "請選擇...",
    "Academic & Skills": "學歷與技能",
    "Academic": "學歷",
    "Select degree...": "選擇學歷...",
    "School Name": "學校名稱",
    "Major": "主修",
    "Occupation": "職業",
    "Job title / Occupation": "職稱 / 職業",
    "Affiliation": "所屬單位",
    "Local shelters, clubs, organizations...": "在地收容所、社團、組織...",
    "Currently own any pets?": "目前有養寵物嗎？",
    "You can add pet profiles later": "你可以稍後新增寵物檔案",
    "Social Availability": "社交意願",
    "Are you open to connecting?": "願意交朋友嗎？",
    "I identify as:": "我的身份是：",
    "Continue to Pet Setup": "繼續設定寵物",
    "Complete Setup": "完成設定",
    "Male": "男性",
    "Female": "女性",
    "Non-binary": "非二元",
    "PNA": "不方便回答",
    "Straight": "異性戀",
    "Gay/Lesbian": "同性戀",
    "Bisexual": "雙性戀",
    "Queer": "酷兒",
    "College": "大學",
    "Associate Degree": "副學士",
    "Bachelor": "學士",
    "Master": "碩士",
    "Doctorate / PhD": "博士",
    "Single": "單身",
    "In a relationship": "交往中",
    "Open relationship": "開放式關係",
    "Married": "已婚",
    "Divorced": "離婚",
    "Dogs": "狗",
    "Cats": "貓",
    "Birds": "鳥",
    "Fish": "魚",
    "Reptiles": "爬蟲類",
    "Small Mammals": "小型哺乳類",
    "Horses": "馬",
    "Exotic Pets": "異寵",
    "Farm Animals": "農場動物",
    "None": "沒有",
    "Pet Parents": "毛孩家長",
    "Pet Nanny": "寵物保姆",
    "Animal Friend (no pet)": "動物友人（無寵物）",
    "English": "英文",
    "Cantonese": "廣東話",
    "Mandarin": "普通話",
    "Spanish": "西班牙文",
    "French": "法文",
    "Japanese": "日文",
    "Korean": "韓文",
    "German": "德文",
    "Portuguese": "葡萄牙文",
    "Italian": "義大利文",
    
    // Pet Profile
    "pet.title": "養寵資料",
    "pet.basics": "基本資料",
    "pet.vault": "健康記錄",
    "pet.lifestyle": "生活習慣",
    "pet.name": "名字",
    "pet.species": "種類",
    "pet.breed": "品種",
    "pet.gender": "性別",
    "pet.weight": "體重",
    "pet.dob": "出生日期",
    "pet.vaccinations": "疫苗接種",
    "pet.medications": "用藥",
    "pet.microchip": "晶片號碼",
    "pet.vet_contact": "獸醫聯絡方式",
    "pet.temperament": "性格",
    "pet.routine": "日常作息",
    
    // Premium
    "premium.title": "huddle 星級會員",
    "Huddle Premium": "huddle 高級會員",
    "premium.unlock": "解鎖完整體驗",
    "premium.upgrade": "成為星級huddler",
    "premium.maybe_later": "稍後再說",
    "premium.compare": "方案比較",
    "premium.free_plan": "免費版",
    "premium.premium_plan": "星級會員",
    "premium.grey_badge": "灰色徽章",
    "premium.gold_badge": "金色徽章",
    "premium.text_ai": "文字AI",
    "premium.photo_audio_ai": "照片/語音AI",
    "premium.alert_1mi": "1英里警報",
    "premium.alert_5mi": "5英里警報",
    "premium.single_filter": "單一篩選",
    "premium.multi_filter": "多重篩選",
    "premium.ghost_mode": "隱身模式",
    "premium.featured": "精選刊登",
    

    // Nanny Booking Modal
    "booking.title": "預約保姆",
    "booking.pet_nanny": "寵物保姆",
    "booking.service_date": "服務日期",
    "booking.start_time": "開始時間",
    "booking.end_time": "結束時間",
    "booking.which_pet": "哪隻寵物？",
    "booking.select_pet": "請選擇寵物…",
    "booking.location": "服務地點",
    "booking.location_not_set": "請在個人資料中設定地點",
    "booking.amount": "預約金額（美元）",
    "booking.amount_note": "最低 $10 · 金額將托管至服務完成",
    "booking.amount_calculated": "價格依保姆時薪自動計算",
    "booking.cancel": "取消",
    "booking.pay": "前往付款",
    "booking.payment_failed": "無法啟動付款",
    // Common
    "common.save": "儲存",
    "Save": "儲存",
    "Legal name is required": "請輸入法定姓名",
    "Display name is required": "請輸入顯示名稱",
    "common.cancel": "取消",
    "common.confirm": "確認",
    "common.delete": "刪除",
    "common.create": "建立",
    "common.add": "新增",
    "common.remove": "移除",
    "common.close": "關閉",
    "common.loading": "載入中...",
    "common.error": "錯誤",
    "common.success": "成功",
    "common.others": "其他",
    "✓": "✓",
    "$9.99": "$9.99",
    "*": "*",
    "$": "$",
    "•": "•",
    "🏥": "🏥",
    "—": "—",
    // Auth
    "auth.login": "登入",
    "auth.signup": "註冊",
    "auth.remember": "記住我",
    "auth.create_account": "建立帳號",
    "auth.use_phone": "改用電話號碼",
    "auth.use_email": "改用電子郵件",
    "auth.apple": "Apple",
    "auth.google": "Google",
    "auth.soon": "即將推出",
    "auth.or_continue": "或使用以下方式繼續",
    "auth.forgot_password": "忘記密碼？",
    "auth.reset_enter_email": "請輸入電子郵件以重設密碼",
    "auth.reset_failed": "重設信件寄送失敗",
    "auth.reset_sent": "重設連結已寄出",
    "auth.by_continuing": "繼續即表示您同意",
    "auth.terms": "服務條款",
    "auth.and": "與",
    "auth.privacy": "隱私權政策",
    "auth.welcome_back": "歡迎回來！",
    "auth.use_email_signup": "請使用電子郵件註冊",
    "auth.account_created": "帳號已建立！讓我們開始設定檔案。",
    "Welcome to Huddle! 🎉": "歡迎加入 huddle！🎉",
    "Welcome to Huddle! You can add pets later.": "歡迎加入 huddle！你可以稍後新增寵物。",
    "auth.errors.invalid_email": "請輸入有效的電子郵件",
    "auth.errors.invalid_phone": "請輸入有效的電話號碼",
    "auth.errors.password_min": "密碼至少 8 碼",
    "auth.errors.password_upper": "密碼需包含至少 1 個大寫字母",
    "auth.errors.password_number": "密碼需包含至少 1 個數字",
    "auth.errors.password_special": "密碼需包含至少 1 個特殊字元",
    "auth.errors.invalid_identifier": "請輸入有效的電子郵件或電話號碼",
    "auth.errors.invalid": "帳號或密碼錯誤",
    "auth.errors.account_exists": "此電子郵件已註冊",
    "auth.errors.display_name_required": "請輸入顯示名稱",
    "auth.errors.legal_name_required": "請輸入法定姓名",
    "error.missing_fields": "請填寫所有必填欄位",
    "auth.password_strength.length": "✓ 至少 8 個字元",
    "auth.password_strength.upper": "✓ 至少 1 個大寫字母",
    "auth.password_strength.number": "✓ 至少 1 個數字",
    "auth.password_strength.special": "✓ 至少 1 個特殊字元",
    // Settings & Identity
    "Invite link copied": "邀請連結已複製",
    "Failed to copy invite link": "複製邀請連結失敗",
    "Share this link to invite a family member to your huddle.": "分享此連結以邀請家人加入你的 huddle。",
    "Copy Invite Link": "複製邀請連結",
    "Verified": "已驗證",
    "Verified Huddler": "已驗證 huddler",
    "Upload a government-issued ID or passport for review. Approval typically takes 24-48 hours.": "上傳政府核發證件或護照以供審核，通常需 24-48 小時。",
    "Click to upload ID/Passport": "點擊上傳證件/護照",
    "Submit": "送出",
    "Update": "更新",
    "Verify": "驗證",
    "First, verify your current password": "請先驗證目前密碼",
    "Place your finger on the sensor": "請將手指放在感應器上",
    "Scanning...": "掃描中...",
    "Success!": "成功！",
    "Touch the fingerprint sensor": "請觸碰指紋感應器",
    "Keep your finger steady": "請保持手指穩定",
    "Biometric authentication enabled": "已啟用生物辨識",
    "This action cannot be undone. All your data will be permanently deleted.": "此操作無法復原，所有資料將被永久刪除。",
    "Verify your identity to unlock full community features": "驗證身份以解鎖完整功能",
    "This is kept private and used only for verification": "此資訊僅用於驗證並保持私密",
    "Submit your ID for review to earn a verified badge": "提交證件審核以獲得驗證徽章",
    "Start Verification": "開始驗證",
    "Submitting for Review...": "送出審核中...",
    "Processing your verification request": "正在處理驗證申請",
    "Verification Submitted": "已提交驗證",
    "Your verification is pending approval": "你的驗證正在等待審核",
    "Skipping verification may affect your user journey": "略過驗證可能影響使用體驗",
    "Unverified users have limited access to certain community features and may appear less trustworthy to others.": "未驗證用戶將受限於部分功能，且可能降低可信度。",
    "Yes, Skip Verification": "是的，略過驗證",
    "Skip for now": "暫時略過",
    "Continue to Profile Setup": "繼續設定個人檔案",
    "Verification submitted for review": "驗證已送出審核",
    // Hazard Scanner
    "Upload a photo of any object your pet found. AI will identify if it's toxic or safe.": "上傳寵物找到的物品照片，AI 會判斷是否有毒。",
    "Preview": "預覽",
    "Change Photo": "更換照片",
    "Scan for Hazards": "掃描危險物",
    "identified as": "判定為",
    "Scan Another Item": "再掃描一項",
    "Call Emergency Vet Now": "立即致電急診獸醫",
    "appears to be safe": "看起來是安全的",
    // Profile & Pets
    "Legal Name": "法定姓名",
    "Your legal name": "你的法定姓名",
    "Your display name": "你的顯示名稱",
    "Phone (+XXX)": "電話 (+XXX)",
    "Select breed": "選擇品種",
    "Siamese": "暹羅",
    "Persian": "波斯",
    "Maine Coon": "緬因庫恩",
    "Ragdoll": "布偶",
    "Bengal": "孟加拉",
    "British Shorthair": "英國短毛",
    "Sphynx": "斯芬克斯",
    "Scottish Fold": "蘇格蘭摺耳",
    "Abyssinian": "阿比西尼亞",
    "Phone number is required": "請輸入電話號碼",
    "Date of birth is required": "請輸入出生日期",
    "Save Pet Profile": "儲存寵物檔案",
    "Friend": "朋友",
    "Weight": "體重",
    "months": "個月",
    "year": "年",
    "years": "年",
    // Premium
    "You're a Gold Member!": "你是金級會員！",
    "You're a Premium Member!": "你是高級會員！",
    "Status:": "狀態：",
    "active": "啟用中",
    "Manage": "管理",
    "Processing...": "處理中...",
    "Upgrade to": "升級為",
    "Buy": "購買",
    "Secure payments powered by Stripe": "安全付款由 Stripe 提供",
    // Premium Feature Table
    "Badge Type": "徽章類型",
    "Grey": "灰色",
    "Blue Premium": "藍色高級",
    "Gold Crown": "金色皇冠",
    "Chat Access": "聊天權限",
    "Limited": "有限",
    "Unlimited": "無限制",
    "Unlimited + Priority": "無限制 + 優先",
    "AI Vet": "AI 獸醫",
    "Text Only": "僅文字",
    "Photo + Audio": "照片 + 音訊",
    "Unlimited Media": "無限媒體",
    "Broadcast Range": "廣播範圍",
    "1 mile": "1 英里",
    "5 miles": "5 英里",
    "10 miles": "10 英里",
    "Social Filters": "社交篩選",
    "Basic": "基本",
    "Advanced": "進階",
    "Advanced + Boosts": "進階 + Boost",
    "Ghost Mode": "幽靈模式",
    "Notice Board": "Threads",
    "Priority Support": "優先支援",
    "Marketplace Priority": "市集優先",
    "Ad-free Experience": "無廣告體驗",
    // Add-ons
    "3 Star Pack": "3 顆星組合",
    "Boost your profile visibility": "提升個人曝光度",
    "Emergency Mesh Alert": "緊急網狀警報",
    "Lost pet emergency broadcast": "走失寵物緊急廣播",
    "10 AI Vet Media Credits": "10 次 AI 獸醫媒體",
    "Upload photos/videos to AI Vet": "上傳照片/影片至 AI 獸醫",
    "Family Member Slot": "家庭成員名額",
    "Add 1 family member to account": "新增 1 位家庭成員",
    "Verified Badge": "已驗證徽章",
    "One-time ID verification": "一次性身分驗證",
    // Pet Wizard / Pet Details
    "Step": "步驟",
    "Keep track of important health info": "記錄重要的健康資訊",
    "Microchip ID (15 digits)": "晶片編號（15 位數）",
    "digits": "位數",
    "About": "關於",
    "Next Reminder": "下次提醒",
    "Help others understand your pet": "幫助他人了解你的寵物",
    "Confirm": "確認",
    "'s details": "的資料",
    "recorded": "筆",
    "Back": "返回",
    "Continue": "繼續",
    "Pet": "寵物",
    // Premium Footer
    "Notice Board is Premium only": "Threads 僅限高級會員",
    "Upgrade to post notices, share updates, and connect with your huddle community.": "升級即可發布公告、分享更新並與社群互動。",
    "Extended Broadcast needs Premium": "擴大廣播需要高級會員",
    "Free users broadcast within 1 km. Upgrade for up to 5 km mesh alerts.": "免費用戶僅限 1 公里廣播。升級可達 5 公里。",
    "Media sharing is a Premium perk": "媒體分享是高級會員功能",
    "Send photos & files in chats. Unlock unlimited media with Premium.": "在聊天中分享照片與檔案。升級享有無限媒體。",
    "Alert limit reached": "警報次數已達上限",
    "Free users get 2 mesh alerts per day. Upgrade for unlimited emergency broadcasts.": "免費用戶每日 2 次警報。升級享有不限次數。",
    "Unlock the full huddle experience": "解鎖完整 huddle 體驗",
    "Premium gives you access to all features — starting at just $8.99/month.": "高級會員提供完整功能，月費僅 $8.99 起。",
    "Verified Status": "已驗證狀態",
    "5 km Broadcast Radius": "5 公里廣播範圍",
    "Notice Board Access": "Threads 權限",
    "Chat Image Access": "聊天圖片權限",
    "Priority Visibility": "優先曝光",
    "Ad-Free Experience": "無廣告體驗",
    "huddle Premium": "huddle 高級會員",
    "Welcome to huddle Premium!": "歡迎加入 huddle 高級會員！",
    "Upgrade Now": "立即升級",
    "Maybe Later": "稍後再說",
    // AI Vet Greeting
    "Hello there! I'm Dr. Huddle, your friendly AI pet assistant. 🐾": "你好！我是 huddle 醫生，你友善的 AI 寵物助手。🐾",
    "I see you've selected": "我看到你選擇了",
    "your": "你的",
    "old": "歲",
    "I'm here to help with any questions about": "我可以協助解答關於",
    "'s health and wellness.": "的健康與照護問題。",
    "While I can provide helpful information and guidance, remember that I'm always happy to point you toward your local vet for hands-on care.": "雖然我可以提供資訊與建議，但仍建議需要時諮詢當地獸醫。",
    "What can I help you with today?": "今天我可以如何幫助你？",
    // Language & Misc
    "language.english": "英文",
    "language.zh_tw": "繁體中文",
    "language.zh_cn": "简体中文",
    "invite.slots_available": "可邀請名額：{count}",
    "invite.no_slots": "沒有可用邀請名額",
    // Map Extensions
    "map.distance_km": "{count} 公里",
    "map.distance_km_max": "{count} 公里（上限）",
    "map.word_count": "{count}/{max} 字",
    "map.add_photo": "新增照片",
    "map.broadcast_alert": "發布 {type} 警報",
    "map.supports": "{count} 支援",
    "map.vet_clinic": "獸醫診所",
    "map.vet.hk_clinic": "香港獸醫診所",
    "map.vet.central_hospital": "中環寵物醫院",
    "map.vet.wan_chai": "灣仔動物護理",
    "map.vet.kowloon": "九龍獸醫中心",
    "map.create_alert_failed": "建立警報失敗",
    // Notice Board
    "notice.category.social": "社交",
    "notice.category.charity": "慈善",
    "notice.category.news": "新聞",
    "notice.dummy_content": "剛領養這隻可愛虎斑貓！🐱 想找附近的貓友交流照顧心得，或安排玩伴。她 2 歲，很愛撒嬌！",
    "notice.dummy_author": "愛貓人士",
    // AI Vet Limits
    "ai.errors.free_limit": "你已達到本月免費訊息上限",
    "ai.fallback_message": "I appreciate your question! Based on what you've described, I'd suggest keeping a close eye on your pet over the next day or two. Monitor for any changes in appetite, energy levels, or the symptoms you mentioned.\n\nIf things don't improve within 48 hours, or if you notice anything concerning, I'd definitely recommend visiting your local vet for a proper check-up. They'll be able to give your pet a hands-on examination.\n\nIn the meantime, I'm here if you have any more questions! 🐕",
    "ai.free_remaining": "本月剩餘 {count} 次免費對話",
    "ai.free_exhausted": "免費對話已用完",
    // Hazard Scanner
    "hazard.image_optimized": "圖片已最佳化（節省 {savedKB} KB）",
    "hazard.rate_limit": "已超出限制。免費版每 24 小時 3 次掃描。升級高級會員可無限制掃描！",
    // Premium misc
    "premium.savings_26": "省下 26%",
    "premium.savings_25": "省下 25%",
    "per_month_short": "{value}/月",
    // Home
    "home.next_event_sample": "中午散步，12:00",
  },
  "zh-CN": {
    // Brand
    "app.name": "huddle",
    "app.subheadline": "宠物照护与社交",
    
    // Navigation
    "nav.home": "首页",
    "nav.social": "社交",
    "nav.chats": "聊天",
    "nav.ai_vet": "AI 兽医",
    "nav.map": "地图",
    
    // Global Header
    "header.free": "免费版",
    "header.premium": "星级会员",
    "header.upgrade": "升级",

    // Auth
    "auth.login": "登录",
    "auth.signup": "注册",
    "auth.remember": "记住我",
    "auth.create_account": "创建账号",
    "auth.use_phone": "改用电话号码",
    "auth.use_email": "改用电子邮件",
    "auth.apple": "Apple",
    "auth.google": "Google",
    "auth.soon": "即将推出",
    "auth.or_continue": "或使用以下方式继续",
    "auth.forgot_password": "忘记密码？",
    "auth.reset_enter_email": "请输入电子邮件以重设密码",
    "auth.reset_failed": "重设邮件发送失败",
    "auth.reset_sent": "重设链接已发送",
    "auth.by_continuing": "继续即表示您同意",
    "auth.terms": "服务条款",
    "auth.and": "与",
    "auth.privacy": "隐私政策",
    "auth.welcome_back": "欢迎回来！",
    "auth.use_email_signup": "请使用电子邮件注册",
    "auth.account_created": "账号已创建！让我们开始设置资料。",
    "Welcome to Huddle! 🎉": "欢迎加入 huddle！🎉",
    "Welcome to Huddle! You can add pets later.": "欢迎加入 huddle！你可以稍后新增宠物。",
    "auth.errors.invalid_email": "请输入有效的电子邮件",
    "auth.errors.invalid_phone": "请输入有效的电话号码",
    "auth.errors.password_min": "密码至少 8 个字符",
    "auth.errors.password_upper": "密码需包含至少 1 个大写字母",
    "auth.errors.password_number": "密码需包含至少 1 个数字",
    "auth.errors.password_special": "密码需包含至少 1 个特殊字符",
    "auth.errors.invalid_identifier": "请输入有效的电子邮件或电话号码",
    "auth.errors.invalid": "账号或密码错误",
    "auth.errors.account_exists": "此电子邮件已注册",
    "auth.errors.display_name_required": "请输入显示名称",
    "auth.errors.legal_name_required": "请输入法定姓名",
    "error.missing_fields": "请填写所有必填字段",
    "auth.password_strength.length": "✓ 至少 8 个字符",
    "auth.password_strength.upper": "✓ 至少 1 个大写字母",
    "auth.password_strength.number": "✓ 至少 1 个数字",
    "auth.password_strength.special": "✓ 至少 1 个特殊字符",
    
    // Home
    "home.greeting": "嗨，{name}！👋",
    "home.subtitle": "一起照顾你的毛孩",
    "home.wisdom": "毛孩百科",
    "home.next_event": "下一个活动",
    "home.wisdom.dog.1": "狗狗每天需要 1-2 小时运动，考虑增加晚间散步！",
    "home.wisdom.dog.2": "定期梳毛可减少掉毛并保持毛发健康。",
    "home.wisdom.dog.3": "心理刺激与身体运动同样重要。",
    "home.wisdom.dog.4": "牙齿保健很重要！每周刷牙 2-3 次可预防疾病。",
    "home.wisdom.cat.1": "猫咪每天需要新鲜饮水，猫饮水机可促进饮水。",
    "home.wisdom.cat.2": "提供抓抓柱能保护家具并维持爪子健康。",
    "home.wisdom.cat.3": "猫咪在清晨与黄昏较活跃，可安排游戏时间。",
    "home.wisdom.cat.4": "定期体检很重要，猫咪常会隐藏病痛。",
    "home.wisdom.bird.1": "鸟类需要 10-12 小时睡眠，夜间可覆盖笼子。",
    "home.wisdom.bird.2": "每日摄取新鲜蔬果有助于营养均衡。",
    "home.wisdom.bird.3": "鸟类需要每日互动与心智刺激。",
    "home.wisdom.bird.4": "每周更换玩具可避免无聊并鼓励觅食行为。",
    "home.wisdom.rabbit.1": "兔子需要无限量牧草以维持消化与牙齿健康。",
    "home.wisdom.rabbit.2": "提供安全空间让兔子奔跑与跳跃，需要每日运动。",
    "home.wisdom.rabbit.3": "定期梳毛可避免毛球，换毛期更重要。",
    "home.wisdom.rabbit.4": "兔子是社交动物，可考虑结伴饲养。",
    "home.wisdom.reptile.1": "爬虫需要 UV 灯与适当温度。",
    "home.wisdom.reptile.2": "不同物种湿度需求不同，请做好研究。",
    "home.wisdom.reptile.3": "钙与维生素 D3 补充可预防代谢性骨病。",
    "home.wisdom.reptile.4": "定期粪检有助于发现寄生虫。",
    "home.wisdom.hamster.1": "仓鼠夜行性，夜间活动与跑轮很常见。",
    "home.wisdom.hamster.2": "提供大笼舍与深垫材以利挖掘。",
    "home.wisdom.hamster.3": "少量新鲜蔬菜是健康零食。",
    "home.wisdom.hamster.4": "黄金鼠需单独饲养，部分侏儒鼠可同居。",
    "home.wisdom.other.1": "每种动物需求不同，请研究其照护方式。",
    "home.wisdom.other.2": "寻找有相关经验的兽医。",
    "home.wisdom.other.3": "加入社群与其他饲主交流经验。",
    "home.wisdom.other.4": "良好饮食与栖地是照护基础。",
    "Your Huddle is Empty": "你的 huddle 还是空的",
    "has been added to your huddle!": "已新增到你的 huddle！",
    
    // Social
    "social.discovery": "探索",
    "social.nearby": "附近的Huddler",
    "social.nannies": "暖心保姆",
    "social.playdates": "毛孩聚会",
    "social.animal_lovers": "动物之友",
    "social.verified": "已认证",
    "social.star_prompt": "购买星星包即可立即与该用户聊天",
    "Buy a star pack to immediately chat with the user": "购买星星包即可立即与该用户聊天",
    "Boost sent": "加速已送出",
    "social.support": "支持",
    "social.report": "举报",
    "social.hide": "隐藏",
    "social.wave": "打招呼",
    "social.match": "双向打招呼！",
    "social.user.marcus.name": "Marcus",
    "social.user.emma.name": "Emma",
    "social.user.james.name": "James",
    "social.location.central_park": "中央公园",
    "social.location.dog_run": "狗狗跑区",
    "social.location.pet_cafe": "宠物咖啡馆",
    "social.profile.sarah.name": "Sarah",
    "social.profile.sarah.location": "中央公园",
    "social.profile.sarah.bio": "喜欢和 Bella 一起徒步、认识新朋友！周末有空一起冒险。",
    "social.profile.sarah.title": "Sarah，31 岁",
    "social.profile.sarah.photo_alt": "Sarah 与 Bella",
    "social.profile.tag.trail_hiker": "#TrailHiker",
    "social.profile.tag.dog_friendly": "#DogFriendly",
    "social.profile.nearby_bio": "友好且乐于结识附近的宠物爱好者。",
    "social.match_message": "你和 Sarah 互相打招呼了，开始聊天吧！",
    "Normal Chat": "普通聊天",
    "Broadcast Alert": "广播警报",
    "You and Sarah waved at each other. Start a chat to say hi!": "你和 Sarah 互相打招呼了，开始聊天吧！",
    "Start Chat": "开始聊天",
    "Chat media": "聊天媒体",
    "Sarah & Bella": "Sarah 与 Bella",
    "Sarah, 31 Years Old": "Sarah，31 岁",
    "#TrailHiker": "#TrailHiker",
    "#DogFriendly": "#DogFriendly",
    "Love hiking with Bella and meeting new friends! Available for weekend adventures.": "喜欢和 Bella 一起徒步、认识新朋友！周末有空一起冒险。",
    "Friendly and open to meeting new pet lovers nearby.": "友好且乐于结识附近的宠物爱好者。",
    "Marcus": "Marcus",
    "Emma": "Emma",
    "James": "James",
    "Central Park": "中央公园",
    "Dog Run": "狗狗跑区",
    "Pet Cafe": "宠物咖啡馆",
    "Let's Get Started": "开始吧",
    "Welcome to huddle": "欢迎加入 huddle",
    "Family mesh for pets": "毛孩家庭网",
    "Please upload a valid ID or passport": "请上传有效的身份证或护照",
    "PNG, JPG, PDF up to 10MB": "PNG、JPG、PDF 最多 10MB",
    "auth.errors.session_expired": "会话已过期，请重新登录。",
    "Please fill in your legal name and phone number first": "请先填写法定姓名与电话号码",
    "has been added to your huddle! 🎉": "已新增到你的 huddle！🎉",
    
    // Dr. Huddle / AI Vet
    "ai.name": "huddle AI 医生",
    "Dr. Huddle": "Dr. huddle",
    "Dr. Huddle is thinking...": "Dr. huddle 正在思考...",
    "ai.online": "在线",
    "ai.analyzing": "正在分析",
    "ai.disclaimer": "huddle AI 医生是仅供参考的人工智能助手。提供的信息可能有误。请务必寻求专业兽医意见。如有疑虑或紧急情况，请立即前往诊所。",
    "ai.placeholder": "输入消息...",
    "ai.attach_pet": "附加宠物资料",
    
    // Map
    "map.search": "搜索狗公园、兽医或朋友...",
    "map.filter_all": "全部",
    "map.filter_stray": "流浪动物",
    "map.filter_lost": "走失宠物",
    "map.filter_found": "已找到",
    "map.filter_friends": "朋友",
    "map.filter_others": "其他",
    "map.go_online": "上线",
    "map.broadcast": "紧急通报",
    "map.broadcast_remark": "通报将发送给{distance}英里内的在线用户；有效期48小时。",
    "map.call_now": "立即拨打",
    "map.navigate": "导航",
    "map.found_btn": "已找到",
    "map.remove_pin": "移除标记？",
    "map.24h": "24小时",
    "See Further": "看更远",
    "Extend search by +5km": "搜索距离增加 +5 公里",
    
    // Chats
    "chats.title": "聊天",
    "chats.new_huddles": "新朋友",
    "chats.create_group": "创建群组",
    "chats.group_name": "群组名称",
    "chats.add_members": "添加成员",
    "chats.allow_control": "允许成员管理群组",
    "chats.tab.chats": "聊天",
    "chats.tab.groups": "群组",
    "chats.connecting": "正在连接到聊天服务器...",
    "chats.create_group_prompt": "创建群组开始聊天！",
    "chats.verify_to_create": "完成认证后才能创建群组",
    "No conversations found": "未找到对话",
    "No groups found": "未找到群组",
    "Load more": "加载更多",
    "Just now": "刚刚",
    "h ago": "小时前",
    "d ago": "天前",
    "✓ Verified": "✓ 已认证",
    "Verified User": "已验证用户",
    "Not Verified": "未验证",
    "One-time purchase": "一次性购买",
    "Buy Now": "立即购买",
    "Premium Tip:": "Premium 提示：",
    "Get unlimited media uploads + more features for just $8.99/month": "每月仅 $8.99 即可享有无限媒体上传与更多功能",
    "Has a Car": "有车",
    
    // Settings
    "settings.title": "设置",
    "settings.account_settings": "账户设置",
    "settings.profile": "个人资料",
    "settings.account_security": "账号与安全",
    "settings.personal_info": "个人信息",
    "settings.password": "密码",
    "settings.biometric": "生物识别登录",
    "settings.2fa": "双重验证",
    "settings.privacy": "隐私",
    "settings.private_account": "私人账号",
    "settings.map_visibility": "地图可见度",
    "settings.trusted_locations": "信任的位置",
    "settings.notifications": "通知",
    "settings.pause_all": "暂停所有通知",
    "settings.social_notif": "社交（打招呼/配对）",
    "settings.safety_notif": "安全（警报）",
    "settings.ai_notif": "huddle AI 医生",
    "settings.email_notif": "电子邮件通知",
    "settings.language": "语言",
    "settings.help_support": "帮助与支持",
    "settings.report_bug": "报告问题",
    "settings.privacy_policy": "隐私政策",
    "settings.terms": "服务条款",
    "family.upsell_title": "家庭邀请仅限 Gold",
    "family.upsell_body": "升级至 Gold 以开启家庭邀请与共享访问。",
    "family.upsell_cta": "升级至 Gold",
    "settings.deactivate": "停用账号",
    "Verification Rejected": "验证被拒",
    "Review Note": "审核备注",
    "settings.delete": "删除账号",
    "settings.logout": "登出",
    "settings.pending": "身份验证中",
    "settings.verified_badge": "认证huddler",
    
    // Profile
    "profile.edit": "编辑个人资料",
    "profile.display_name": "显示名称",
    "profile.bio": "简介",
    "profile.gender": "性别",
    "profile.genre": "性向",
    "profile.dob": "出生日期",
    "profile.height": "身高",
    "profile.degree": "最高学历",
    "profile.occupation": "职业",
    "profile.school": "学校",
    "profile.major": "专业",
    "profile.affiliation": "隶属组织",
    "profile.has_car": "有车？",
    "profile.owns_pets": "目前有养宠物？",
    "profile.show": "显示",
    
    // Onboarding Profile Setup
    "Display Name": "显示名称",
    "Legal Name": "法定姓名",
    "Your legal name": "你的法定姓名",
    "Your display name": "你的显示名称",
    "Phone (+XXX)": "电话 (+XXX)",
    "Select breed": "选择品种",
    "Siamese": "暹罗",
    "Persian": "波斯",
    "Maine Coon": "缅因库恩",
    "Ragdoll": "布偶",
    "Bengal": "孟加拉",
    "British Shorthair": "英国短毛",
    "Sphynx": "斯芬克斯",
    "Scottish Fold": "苏格兰折耳",
    "Abyssinian": "阿比西尼亚",
    "How should others call you?": "希望别人怎么称呼你？",
    "Phone (Optional)": "电话（选填）",
    "+1 234 567 8900": "+1 234 567 8900",
    "Bio": "简介",
    "Tell us about yourself...": "介绍一下你自己...",
    "Demographics": "基本资料",
    "Gender": "性别",
    "Sexual Orientation": "性向",
    "Orientation": "性向",
    "Date of Birth": "出生日期",
    "Age": "年龄",
    "Location": "地点",
    "Your city": "你的城市",
    "Pet Experience": "宠物经验",
    "Years of experience": "经验年数",
    "Pet Driver": "宠物载运",
    "I have a car and can transport pets": "我有车可载运宠物",
    "Languages": "语言",
    "Social Level Boosters": "社交加成",
    "Height (cm)": "身高（厘米）",
    "Height": "身高",
    "Your height in cm": "你的身高（厘米）",
    "Weight": "体重",
    "kg": "公斤",
    "lbs": "磅",
    "Relationship Status": "感情状态",
    "Select...": "请选择...",
    "Academic & Skills": "学历与技能",
    "Academic": "学历",
    "Select degree...": "选择学历...",
    "School Name": "学校名称",
    "Major": "主修",
    "Occupation": "职业",
    "Job title / Occupation": "职位 / 职业",
    "Affiliation": "所属单位",
    "Local shelters, clubs, organizations...": "当地收容所、社团、组织...",
    "Currently own any pets?": "目前有养宠物吗？",
    "You can add pet profiles later": "你可以稍后新增宠物档案",
    "Social Availability": "社交意愿",
    "Are you open to connecting?": "愿意交朋友吗？",
    "I identify as:": "我的身份是：",
    "Continue to Pet Setup": "继续设置宠物",
    "Complete Setup": "完成设置",
    "Male": "男性",
    "Female": "女性",
    "Non-binary": "非二元",
    "PNA": "不方便回答",
    "Straight": "异性恋",
    "Gay/Lesbian": "同性恋",
    "Bisexual": "双性恋",
    "Queer": "酷儿",
    "College": "大学",
    "Associate Degree": "副学士",
    "Bachelor": "学士",
    "Master": "硕士",
    "Doctorate / PhD": "博士",
    "Single": "单身",
    "In a relationship": "交往中",
    "Open relationship": "开放式关系",
    "Married": "已婚",
    "Divorced": "离婚",
    "Dogs": "狗",
    "Cats": "猫",
    "Birds": "鸟",
    "Fish": "鱼",
    "Reptiles": "爬虫类",
    "Small Mammals": "小型哺乳类",
    "Horses": "马",
    "Exotic Pets": "异宠",
    "Farm Animals": "农场动物",
    "None": "没有",
    "Pet Parents": "毛孩家长",
    "Pet Nanny": "宠物保姆",
    "Animal Friend (no pet)": "动物友人（无宠物）",
    "English": "英文",
    "Cantonese": "粤语",
    "Mandarin": "普通话",
    "Spanish": "西班牙语",
    "French": "法语",
    "Japanese": "日语",
    "Korean": "韩语",
    "German": "德语",
    "Portuguese": "葡萄牙语",
    "Italian": "意大利语",
    
    // Pet Profile
    "pet.title": "养宠资料",
    "pet.basics": "基本资料",
    "pet.vault": "健康记录",
    "pet.lifestyle": "生活习惯",
    "pet.name": "名字",
    "pet.species": "种类",
    "pet.breed": "品种",
    "pet.gender": "性别",
    "pet.weight": "体重",
    "pet.dob": "出生日期",
    "pet.vaccinations": "疫苗接种",
    "pet.medications": "用药",
    "pet.microchip": "芯片号码",
    "pet.vet_contact": "兽医联系方式",
    "pet.temperament": "性格",
    "pet.routine": "日常作息",
    
    // Premium
    "premium.title": "huddle 星级会员",
    "Huddle Premium": "huddle 高级会员",
    "huddle Premium": "huddle 高级会员",
    "Welcome to huddle Premium!": "欢迎加入 huddle 高级会员！",
    "Verified Huddler": "已验证 huddler",
    "premium.unlock": "解锁完整体验",
    "premium.upgrade": "成为星级huddler",
    "premium.maybe_later": "稍后再说",
    "premium.compare": "方案比较",
    "premium.free_plan": "免费版",
    "premium.premium_plan": "星级会员",
    "premium.grey_badge": "灰色徽章",
    "premium.gold_badge": "金色徽章",
    "premium.text_ai": "文字AI",
    "premium.photo_audio_ai": "照片/语音AI",
    "premium.alert_1mi": "1英里警报",
    "premium.alert_5mi": "5英里警报",
    "premium.single_filter": "单一筛选",
    "premium.multi_filter": "多重筛选",
    "premium.ghost_mode": "隐身模式",
    "premium.featured": "精选刊登",
    

    // Nanny Booking Modal
    "booking.title": "预约保姆",
    "booking.pet_nanny": "宠物保姆",
    "booking.service_date": "服务日期",
    "booking.start_time": "开始时间",
    "booking.end_time": "结束时间",
    "booking.which_pet": "哪只宠物？",
    "booking.select_pet": "请选择宠物…",
    "booking.location": "服务地点",
    "booking.location_not_set": "请在个人资料中设置地点",
    "booking.amount": "预约金额（美元）",
    "booking.amount_note": "最低 $10 · 金额将托管至服务完成",
    "booking.amount_calculated": "价格按保姆时薪自动计算",
    "booking.cancel": "取消",
    "booking.pay": "前往付款",
    "booking.payment_failed": "无法启动付款",
    // Common
    "common.save": "保存",
    "Save": "保存",
    "Legal name is required": "请输入法定姓名",
    "Display name is required": "请输入显示名称",
    "common.cancel": "取消",
    "common.confirm": "确认",
    "common.delete": "删除",
    "common.create": "创建",
    "common.add": "添加",
    "common.remove": "移除",
    "common.close": "关闭",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功",
    "common.others": "其他",
    "✓": "✓",
    "$9.99": "$9.99",
    // Language & Misc
    "language.english": "英文",
    "language.zh_tw": "繁體中文",
    "language.zh_cn": "简体中文",
    "invite.slots_available": "可邀请名额：{count}",
    "invite.no_slots": "没有可用邀请名额",
    // Map Extensions
    "map.distance_km": "{count} 公里",
    "map.distance_km_max": "{count} 公里（上限）",
    "map.word_count": "{count}/{max} 字",
    "map.add_photo": "添加照片",
    "map.broadcast_alert": "发布 {type} 警报",
    "map.supports": "{count} 支持",
    "map.vet_clinic": "兽医诊所",
    "map.vet.hk_clinic": "香港兽医诊所",
    "map.vet.central_hospital": "中环宠物医院",
    "map.vet.wan_chai": "湾仔动物护理",
    "map.vet.kowloon": "九龙兽医中心",
    "map.create_alert_failed": "创建警报失败",
    // Notice Board
    "notice.category.social": "社交",
    "notice.category.charity": "慈善",
    "notice.category.news": "新闻",
    "notice.dummy_content": "刚领养这只可爱虎斑猫！🐱 想找附近的猫友交流照护心得，或安排玩伴。她 2 岁，很爱撒娇！",
    "notice.dummy_author": "爱猫人士",
    // AI Vet Limits
    "ai.errors.free_limit": "你已达到本月免费消息上限",
    "ai.fallback_message": "I appreciate your question! Based on what you've described, I'd suggest keeping a close eye on your pet over the next day or two. Monitor for any changes in appetite, energy levels, or the symptoms you mentioned.\n\nIf things don't improve within 48 hours, or if you notice anything concerning, I'd definitely recommend visiting your local vet for a proper check-up. They'll be able to give your pet a hands-on examination.\n\nIn the meantime, I'm here if you have any more questions! 🐕",
    "ai.free_remaining": "本月剩余 {count} 次免费对话",
    "ai.free_exhausted": "免费对话已用完",
    // Hazard Scanner
    "hazard.image_optimized": "图片已优化（节省 {savedKB} KB）",
    "hazard.rate_limit": "已超出限制。免费版每 24 小时 3 次扫描。升级高级会员可无限扫描！",
    // Premium misc
    "premium.savings_26": "省下 26%",
    "premium.savings_25": "省下 25%",
    "per_month_short": "{value}/月",
    // Home
    "home.next_event_sample": "中午散步，12:00",
  },
};

// Detect device language
const detectLanguage = (): Language => {
  const browserLang = navigator.language.toLowerCase();
  if (browserLang.startsWith("zh-tw") || browserLang.startsWith("zh-hant")) {
    return "zh-TW";
  } else if (browserLang.startsWith("zh")) {
    return "zh-CN";
  }
  return "en";
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("huddle_language");
    if (saved && (saved === "en" || saved === "zh-TW" || saved === "zh-CN")) {
      return saved as Language;
    }
    return detectLanguage();
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("huddle_language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language === "zh-TW" ? "zh-Hant" : language === "zh-CN" ? "zh-Hans" : "en";
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
