import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "zh-TW" | "zh-CN";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Brand
    "app.name": "huddle",
    "app.subheadline": "Pet care & social",
    
    // Navigation
    "nav.home": "Home",
    "nav.social": "Social",
    "nav.chats": "Chats",
    "nav.ai_vet": "AI Vet",
    "nav.map": "Map",
    
    // Global Header
    "header.free": "Free",
    "header.premium": "Premium",
    "header.upgrade": "Upgrade",
    
    // Home
    "home.greeting": "Hi, {name}! 👋",
    "home.subtitle": "Let's care for your pets",
    "home.wisdom": "Huddle Wisdom",
    "home.next_event": "Next Event",
    
    // Social
    "social.discovery": "Discovery",
    "social.nearby": "Huddle Nearby",
    "social.nannies": "Nannies",
    "social.playdates": "Playdates",
    "social.animal_lovers": "Animal Lovers",
    "social.verified": "Verified",
    "social.support": "Support",
    "social.report": "Report",
    "social.hide": "Hide",
    "social.wave": "Wave",
    "social.match": "Double Wave!",
    
    // Dr. Huddle / AI Vet
    "ai.name": "Dr. Huddle",
    "ai.online": "Online",
    "ai.analyzing": "Analyzing for",
    "ai.disclaimer": "Dr. Huddle is an AI assistant for informational purposes only. Information provided can be wrong. Always seek professional veterinary opinions. Visit a clinic immediately if you have doubts or an emergency.",
    "ai.placeholder": "Type a message...",
    "ai.attach_pet": "Attach Pet Profile",
    
    // Map
    "map.search": "Find dog parks, vets, or friends...",
    "map.filter_all": "All",
    "map.filter_stray": "Stray",
    "map.filter_lost": "Lost",
    "map.filter_found": "Found",
    "map.filter_friends": "Friends",
    "map.filter_others": "Others",
    "map.go_online": "Go Online",
    "map.broadcast": "Broadcast Alert",
    "map.broadcast_remark": "Broadcasts to online users within {distance} miles; active for 48 hours.",
    "map.call_now": "Call Now",
    "map.navigate": "Navigate",
    "map.found_btn": "Found",
    "map.remove_pin": "Remove Pin?",
    "map.24h": "24h",
    
    // Chats
    "chats.title": "Chats",
    "chats.new_huddles": "New Huddles",
    "chats.create_group": "Create Group",
    "chats.group_name": "Group Name",
    "chats.add_members": "Add Members",
    "chats.allow_control": "Allow members to manage group",
    
    // Settings
    "settings.title": "Settings",
    "Account Settings": "Account Settings",
    "settings.profile": "Profile",
    "settings.account_security": "Account & Security",
    "settings.personal_info": "Personal Info",
    "settings.password": "Password",
    "settings.biometric": "Biometric Login",
    "settings.2fa": "Two-Factor Auth",
    "settings.privacy": "Privacy",
    "settings.private_account": "Private Account",
    "settings.map_visibility": "Map Visibility",
    "settings.trusted_locations": "Trusted Locations",
    "settings.notifications": "Notifications",
    "settings.pause_all": "Pause All",
    "settings.social_notif": "Social (Waves/Matches)",
    "settings.safety_notif": "Safety (Alerts)",
    "settings.ai_notif": "Dr. Huddle",
    "settings.email_notif": "Email Notifications",
    "settings.language": "Language",
    "settings.help_support": "Help & Support",
    "settings.report_bug": "Report a Bug",
    "settings.privacy_policy": "Privacy Policy",
    "settings.terms": "Terms of Service",
    "settings.deactivate": "Deactivate Account",
    "settings.delete": "Delete Account",
    "settings.logout": "Logout",
    "settings.pending": "Identity pending",
    "settings.verified_badge": "Verified huddler",
    
    // Profile
    "profile.edit": "Edit Profile",
    "profile.display_name": "Display Name",
    "profile.bio": "Bio",
    "profile.gender": "Gender",
    "profile.genre": "Genre/Orientation",
    "profile.dob": "Date of Birth",
    "profile.height": "Height",
    "profile.degree": "Highest Degree",
    "profile.occupation": "Occupation",
    "profile.school": "School",
    "profile.major": "Major",
    "profile.affiliation": "Affiliation",
    "profile.has_car": "Own a Car?",
    "profile.owns_pets": "Currently own pets?",
    "profile.show": "Show",
    
    // Pet Profile
    "pet.title": "Pet Profile",
    "pet.basics": "Basics",
    "pet.vault": "The Vault",
    "pet.lifestyle": "Lifestyle",
    "pet.name": "Name",
    "pet.species": "Species",
    "pet.breed": "Breed",
    "pet.gender": "Gender",
    "pet.weight": "Weight",
    "pet.dob": "Date of Birth",
    "pet.vaccinations": "Vaccinations",
    "pet.medications": "Medications",
    "pet.microchip": "Microchip ID",
    "pet.vet_contact": "Vet Contact",
    "pet.temperament": "Temperament",
    "pet.routine": "Routine",
    
    // Premium
    "premium.title": "Huddle Premium",
    "premium.unlock": "Unlock the full experience",
    "premium.upgrade": "Upgrade to Premium",
    "premium.maybe_later": "Maybe later",
    "premium.compare": "Compare Plans",
    "premium.free_plan": "Free",
    "premium.premium_plan": "Premium",
    "premium.grey_badge": "Grey Badge",
    "premium.gold_badge": "Gold Badge",
    "premium.text_ai": "Text AI",
    "premium.photo_audio_ai": "Photo/Audio AI",
    "premium.alert_1mi": "1-mile Alert",
    "premium.alert_5mi": "5-mile Alert",
    "premium.single_filter": "Single Filter",
    "premium.multi_filter": "Multi-select Filters",
    "premium.ghost_mode": "Ghost Mode",
    "premium.featured": "Featured Posting",
    

    // Nanny Booking Modal
    "booking.title": "Book Nanny",
    "booking.pet_nanny": "Pet Nanny",
    "booking.service_date": "Service Date",
    "booking.start_time": "Start Time",
    "booking.end_time": "End Time",
    "booking.which_pet": "Which Pet?",
    "booking.select_pet": "Select a pet…",
    "booking.location": "Service Location",
    "booking.location_not_set": "Set location in your profile",
    "booking.amount": "Booking Amount (USD)",
    "booking.amount_note": "Minimum $10 · Payment held in escrow until service completed",
    "booking.amount_calculated": "Price is calculated from sitter hourly rate",
    "booking.cancel": "Cancel",
    "booking.pay": "Pay via Stripe",
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.delete": "Delete",
    "common.create": "Create",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.others": "Others",
    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.remember": "Remember Me",
    "auth.create_account": "Create Account",
    "auth.use_phone": "Use phone number instead",
    "auth.use_email": "Use email instead",
    "auth.apple": "Apple",
    "auth.google": "Google",
    "auth.soon": "Soon",
    "auth.or_continue": "Or continue with",
    "auth.forgot_password": "Forgot Password?",
    "auth.reset_enter_email": "Enter your email address to reset password",
    "auth.reset_failed": "Failed to send reset email",
    "auth.reset_sent": "Reset link sent to your email!",
    "auth.by_continuing": "By continuing, you agree to our",
    "auth.terms": "Terms of Service",
    "auth.and": "and",
    "auth.privacy": "Privacy Policy",
    "auth.welcome_back": "Welcome back!",
    "auth.use_email_signup": "Please use an email address to sign up",
    "auth.account_created": "Account created! Let's set up your profile.",
    "auth.errors.invalid_email": "Please enter a valid email address",
    "auth.errors.invalid_phone": "Please enter a valid phone number",
    "auth.errors.password_min": "Password must be at least 8 characters",
    "auth.errors.password_upper": "Password must contain at least 1 uppercase letter",
    "auth.errors.password_number": "Password must contain at least 1 number",
    "auth.errors.password_special": "Password must contain at least 1 special character",
    "auth.errors.invalid_identifier": "Please enter a valid email or phone number",
    "auth.errors.invalid": "Invalid email/phone or password",
    "auth.errors.account_exists": "An account with this email already exists",
    "auth.password_strength.length": "✓ At least 8 characters",
    "auth.password_strength.upper": "✓ One uppercase letter",
    "auth.password_strength.number": "✓ One number",
    "auth.password_strength.special": "✓ One special character",
    // Social
    "You and Sarah waved at each other. Start a chat to say hi!": "You and Sarah waved at each other. Start a chat to say hi!",
    "Start Chat": "Start Chat",
    // Settings & Identity
    "Invite link copied": "Invite link copied",
    "Failed to copy invite link": "Failed to copy invite link",
    "Share this link to invite a family member to your huddle.": "Share this link to invite a family member to your huddle.",
    "Copy Invite Link": "Copy Invite Link",
    "Verified": "Verified",
    "Verified Huddler": "Verified Huddler",
    "Upload a government-issued ID or passport for review. Approval typically takes 24-48 hours.": "Upload a government-issued ID or passport for review. Approval typically takes 24-48 hours.",
    "Click to upload ID/Passport": "Click to upload ID/Passport",
    "Submit": "Submit",
    "Update": "Update",
    "Verify": "Verify",
    "First, verify your current password": "First, verify your current password",
    "Place your finger on the sensor": "Place your finger on the sensor",
    "Scanning...": "Scanning...",
    "Success!": "Success!",
    "Touch the fingerprint sensor": "Touch the fingerprint sensor",
    "Keep your finger steady": "Keep your finger steady",
    "Biometric authentication enabled": "Biometric authentication enabled",
    "This action cannot be undone. All your data will be permanently deleted.": "This action cannot be undone. All your data will be permanently deleted.",
    "Verify your identity to unlock full community features": "Verify your identity to unlock full community features",
    "This is kept private and used only for verification": "This is kept private and used only for verification",
    "Submit your ID for review to earn a verified badge": "Submit your ID for review to earn a verified badge",
    "Start Verification": "Start Verification",
    "Submitting for Review...": "Submitting for Review...",
    "Processing your verification request": "Processing your verification request",
    "Verification Submitted": "Verification Submitted",
    "Your verification is pending approval": "Your verification is pending approval",
    "Skipping verification may affect your user journey": "Skipping verification may affect your user journey",
    "Unverified users have limited access to certain community features and may appear less trustworthy to others.": "Unverified users have limited access to certain community features and may appear less trustworthy to others.",
    "Yes, Skip Verification": "Yes, Skip Verification",
    "Skip for now": "Skip for now",
    "Continue to Profile Setup": "Continue to Profile Setup",
    "Verification submitted for review": "Verification submitted for review",
    // Hazard Scanner
    "Upload a photo of any object your pet found. AI will identify if it's toxic or safe.": "Upload a photo of any object your pet found. AI will identify if it's toxic or safe.",
    "Preview": "Preview",
    "Change Photo": "Change Photo",
    "Scan for Hazards": "Scan for Hazards",
    "identified as": "identified as",
    "Scan Another Item": "Scan Another Item",
    "Call Emergency Vet Now": "Call Emergency Vet Now",
    "appears to be safe": "appears to be safe",
    // Profile & Pets
    "Legal Name": "Legal Name",
    "Your legal name": "Your legal name",
    "Legal name is required": "Legal name is required",
    "Phone number is required": "Phone number is required",
    "Date of birth is required": "Date of birth is required",
    "Save Pet Profile": "Save Pet Profile",
    "months": "months",
    "year": "year",
    "years": "years",
    // Premium
    "You're a Gold Member!": "You're a Gold Member!",
    "You're a Premium Member!": "You're a Premium Member!",
    "Status:": "Status:",
    "active": "active",
    "Manage": "Manage",
    "Processing...": "Processing...",
    "Upgrade to": "Upgrade to",
    "Buy": "Buy",
    "Secure payments powered by Stripe": "Secure payments powered by Stripe",
    // Premium Feature Table
    "Badge Type": "Badge Type",
    "Grey": "Grey",
    "Blue Premium": "Blue Premium",
    "Gold Crown": "Gold Crown",
    "Chat Access": "Chat Access",
    "Limited": "Limited",
    "Unlimited": "Unlimited",
    "Unlimited + Priority": "Unlimited + Priority",
    "AI Vet": "AI Vet",
    "Text Only": "Text Only",
    "Photo + Audio": "Photo + Audio",
    "Unlimited Media": "Unlimited Media",
    "Broadcast Range": "Broadcast Range",
    "1 mile": "1 mile",
    "5 miles": "5 miles",
    "10 miles": "10 miles",
    "Social Filters": "Social Filters",
    "Basic": "Basic",
    "Advanced": "Advanced",
    "Advanced + Boosts": "Advanced + Boosts",
    "Ghost Mode": "Ghost Mode",
    "Notice Board": "Notice Board",
    "Priority Support": "Priority Support",
    "Marketplace Priority": "Marketplace Priority",
    "Ad-free Experience": "Ad-free Experience",
    // Add-ons
    "3 Star Pack": "3 Star Pack",
    "Boost your profile visibility": "Boost your profile visibility",
    "Emergency Mesh Alert": "Emergency Mesh Alert",
    "Lost pet emergency broadcast": "Lost pet emergency broadcast",
    "10 AI Vet Media Credits": "10 AI Vet Media Credits",
    "Upload photos/videos to AI Vet": "Upload photos/videos to AI Vet",
    "Family Member Slot": "Family Member Slot",
    "Add 1 family member to account": "Add 1 family member to account",
    "Verified Badge": "Verified Badge",
    "One-time ID verification": "One-time ID verification",
  },
  "zh-TW": {
    // Brand
    "app.name": "huddle",
    "app.subheadline": "寵物照護與社交",
    
    // Navigation
    "nav.home": "首頁",
    "nav.social": "社交",
    "nav.chats": "聊天",
    "nav.ai_vet": "AI 獸醫",
    "nav.map": "地圖",
    
    // Global Header
    "header.free": "免費版",
    "header.premium": "星級會員",
    "header.upgrade": "升級",
    
    // Home
    "home.greeting": "嗨，{name}！👋",
    "home.subtitle": "一起照顧你的毛孩",
    "home.wisdom": "毛孩百科",
    "home.next_event": "下一個活動",
    
    // Social
    "social.discovery": "探索",
    "social.nearby": "附近的Huddler",
    "social.nannies": "暖心保姆",
    "social.playdates": "毛孩聚會",
    "social.animal_lovers": "動物之友",
    "social.verified": "已認證",
    "social.support": "支持",
    "social.report": "檢舉",
    "social.hide": "隱藏",
    "social.wave": "打招呼",
    "social.match": "雙向打招呼！",
    
    // Dr. Huddle / AI Vet
    "ai.name": "Huddle AI 醫生",
    "ai.online": "線上",
    "ai.analyzing": "正在分析",
    "ai.disclaimer": "Huddle AI 醫生是僅供參考的人工智慧助手。提供的資訊可能有誤。請務必尋求專業獸醫意見。如有疑慮或緊急情況，請立即前往診所。",
    "ai.placeholder": "輸入訊息...",
    "ai.attach_pet": "附加寵物資料",
    
    // Map
    "map.search": "搜尋狗公園、獸醫或朋友...",
    "map.filter_all": "全部",
    "map.filter_stray": "流浪動物",
    "map.filter_lost": "走失寵物",
    "map.filter_found": "已找到",
    "map.filter_friends": "朋友",
    "map.filter_others": "其他",
    "map.go_online": "上線",
    "map.broadcast": "緊急通報",
    "map.broadcast_remark": "通報將發送給{distance}英里內的線上用戶；有效期48小時。",
    "map.call_now": "立即撥打",
    "map.navigate": "導航",
    "map.found_btn": "已找到",
    "map.remove_pin": "移除標記？",
    "map.24h": "24小時",
    
    // Chats
    "chats.title": "聊天",
    "chats.new_huddles": "新朋友",
    "chats.create_group": "建立群組",
    "chats.group_name": "群組名稱",
    "chats.add_members": "新增成員",
    "chats.allow_control": "允許成員管理群組",
    
    // Settings
    "settings.title": "設定",
    "Account Settings": "帳號設定",
    "settings.profile": "個人資料",
    "settings.account_security": "帳號與安全",
    "settings.personal_info": "個人資訊",
    "settings.password": "密碼",
    "settings.biometric": "生物辨識登入",
    "settings.2fa": "雙重驗證",
    "settings.privacy": "隱私",
    "settings.private_account": "私人帳號",
    "settings.map_visibility": "地圖可見度",
    "settings.trusted_locations": "信任的位置",
    "settings.notifications": "通知",
    "settings.pause_all": "暫停所有通知",
    "settings.social_notif": "社交（打招呼/配對）",
    "settings.safety_notif": "安全（警報）",
    "settings.ai_notif": "Huddle AI 醫生",
    "settings.email_notif": "電子郵件通知",
    "settings.language": "語言",
    "settings.help_support": "說明與支援",
    "settings.report_bug": "回報問題",
    "settings.privacy_policy": "隱私權政策",
    "settings.terms": "服務條款",
    "settings.deactivate": "停用帳號",
    "settings.delete": "刪除帳號",
    "settings.logout": "登出",
    "settings.pending": "身份驗證中",
    "settings.verified_badge": "認證huddler",
    
    // Profile
    "profile.edit": "編輯個人資料",
    "profile.display_name": "顯示名稱",
    "profile.bio": "簡介",
    "profile.gender": "性別",
    "profile.genre": "性向",
    "profile.dob": "出生日期",
    "profile.height": "身高",
    "profile.degree": "最高學歷",
    "profile.occupation": "職業",
    "profile.school": "學校",
    "profile.major": "主修",
    "profile.affiliation": "隸屬組織",
    "profile.has_car": "有車？",
    "profile.owns_pets": "目前有養寵物？",
    "profile.show": "顯示",
    
    // Pet Profile
    "pet.title": "養寵資料",
    "pet.basics": "基本資料",
    "pet.vault": "健康記錄",
    "pet.lifestyle": "生活習慣",
    "pet.name": "名字",
    "pet.species": "種類",
    "pet.breed": "品種",
    "pet.gender": "性別",
    "pet.weight": "體重",
    "pet.dob": "出生日期",
    "pet.vaccinations": "疫苗接種",
    "pet.medications": "用藥",
    "pet.microchip": "晶片號碼",
    "pet.vet_contact": "獸醫聯絡方式",
    "pet.temperament": "性格",
    "pet.routine": "日常作息",
    
    // Premium
    "premium.title": "Huddle 星級會員",
    "premium.unlock": "解鎖完整體驗",
    "premium.upgrade": "成為星級huddler",
    "premium.maybe_later": "稍後再說",
    "premium.compare": "方案比較",
    "premium.free_plan": "免費版",
    "premium.premium_plan": "星級會員",
    "premium.grey_badge": "灰色徽章",
    "premium.gold_badge": "金色徽章",
    "premium.text_ai": "文字AI",
    "premium.photo_audio_ai": "照片/語音AI",
    "premium.alert_1mi": "1英里警報",
    "premium.alert_5mi": "5英里警報",
    "premium.single_filter": "單一篩選",
    "premium.multi_filter": "多重篩選",
    "premium.ghost_mode": "隱身模式",
    "premium.featured": "精選刊登",
    

    // Nanny Booking Modal
    "booking.title": "預約保姆",
    "booking.pet_nanny": "寵物保姆",
    "booking.service_date": "服務日期",
    "booking.start_time": "開始時間",
    "booking.end_time": "結束時間",
    "booking.which_pet": "哪隻寵物？",
    "booking.select_pet": "請選擇寵物…",
    "booking.location": "服務地點",
    "booking.location_not_set": "請在個人資料中設定地點",
    "booking.amount": "預約金額（美元）",
    "booking.amount_note": "最低 $10 · 金額將托管至服務完成",
    "booking.amount_calculated": "價格依保姆時薪自動計算",
    "booking.cancel": "取消",
    "booking.pay": "前往付款",
    // Common
    "common.save": "儲存",
    "common.cancel": "取消",
    "common.confirm": "確認",
    "common.delete": "刪除",
    "common.create": "建立",
    "common.add": "新增",
    "common.remove": "移除",
    "common.close": "關閉",
    "common.loading": "載入中...",
    "common.error": "錯誤",
    "common.success": "成功",
    "common.others": "其他",
    // Auth
    "auth.login": "登入",
    "auth.signup": "註冊",
    "auth.remember": "記住我",
    "auth.create_account": "建立帳號",
    "auth.use_phone": "改用電話號碼",
    "auth.use_email": "改用電子郵件",
    "auth.apple": "Apple",
    "auth.google": "Google",
    "auth.soon": "即將推出",
    "auth.or_continue": "或使用以下方式繼續",
    "auth.forgot_password": "忘記密碼？",
    "auth.reset_enter_email": "請輸入電子郵件以重設密碼",
    "auth.reset_failed": "重設信件寄送失敗",
    "auth.reset_sent": "重設連結已寄出",
    "auth.by_continuing": "繼續即表示您同意",
    "auth.terms": "服務條款",
    "auth.and": "與",
    "auth.privacy": "隱私權政策",
    "auth.welcome_back": "歡迎回來！",
    "auth.use_email_signup": "請使用電子郵件註冊",
    "auth.account_created": "帳號已建立！讓我們開始設定檔案。",
    "auth.errors.invalid_email": "請輸入有效的電子郵件",
    "auth.errors.invalid_phone": "請輸入有效的電話號碼",
    "auth.errors.password_min": "密碼至少 8 碼",
    "auth.errors.password_upper": "密碼需包含至少 1 個大寫字母",
    "auth.errors.password_number": "密碼需包含至少 1 個數字",
    "auth.errors.password_special": "密碼需包含至少 1 個特殊字元",
    "auth.errors.invalid_identifier": "請輸入有效的電子郵件或電話號碼",
    "auth.errors.invalid": "帳號或密碼錯誤",
    "auth.errors.account_exists": "此電子郵件已註冊",
    "auth.password_strength.length": "✓ 至少 8 個字元",
    "auth.password_strength.upper": "✓ 至少 1 個大寫字母",
    "auth.password_strength.number": "✓ 至少 1 個數字",
    "auth.password_strength.special": "✓ 至少 1 個特殊字元",
    // Social
    "You and Sarah waved at each other. Start a chat to say hi!": "你和 Sarah 互相打招呼了，開始聊天吧！",
    "Start Chat": "開始聊天",
    // Settings & Identity
    "Invite link copied": "邀請連結已複製",
    "Failed to copy invite link": "複製邀請連結失敗",
    "Share this link to invite a family member to your huddle.": "分享此連結以邀請家人加入你的 huddle。",
    "Copy Invite Link": "複製邀請連結",
    "Verified": "已驗證",
    "Verified Huddler": "已驗證 Huddler",
    "Upload a government-issued ID or passport for review. Approval typically takes 24-48 hours.": "上傳政府核發證件或護照以供審核，通常需 24-48 小時。",
    "Click to upload ID/Passport": "點擊上傳證件/護照",
    "Submit": "送出",
    "Update": "更新",
    "Verify": "驗證",
    "First, verify your current password": "請先驗證目前密碼",
    "Place your finger on the sensor": "請將手指放在感應器上",
    "Scanning...": "掃描中...",
    "Success!": "成功！",
    "Touch the fingerprint sensor": "請觸碰指紋感應器",
    "Keep your finger steady": "請保持手指穩定",
    "Biometric authentication enabled": "已啟用生物辨識",
    "This action cannot be undone. All your data will be permanently deleted.": "此操作無法復原，所有資料將被永久刪除。",
    "Verify your identity to unlock full community features": "驗證身份以解鎖完整功能",
    "This is kept private and used only for verification": "此資訊僅用於驗證並保持私密",
    "Submit your ID for review to earn a verified badge": "提交證件審核以獲得驗證徽章",
    "Start Verification": "開始驗證",
    "Submitting for Review...": "送出審核中...",
    "Processing your verification request": "正在處理驗證申請",
    "Verification Submitted": "已提交驗證",
    "Your verification is pending approval": "你的驗證正在等待審核",
    "Skipping verification may affect your user journey": "略過驗證可能影響使用體驗",
    "Unverified users have limited access to certain community features and may appear less trustworthy to others.": "未驗證用戶將受限於部分功能，且可能降低可信度。",
    "Yes, Skip Verification": "是的，略過驗證",
    "Skip for now": "暫時略過",
    "Continue to Profile Setup": "繼續設定個人檔案",
    "Verification submitted for review": "驗證已送出審核",
    // Hazard Scanner
    "Upload a photo of any object your pet found. AI will identify if it's toxic or safe.": "上傳寵物找到的物品照片，AI 會判斷是否有毒。",
    "Preview": "預覽",
    "Change Photo": "更換照片",
    "Scan for Hazards": "掃描危險物",
    "identified as": "判定為",
    "Scan Another Item": "再掃描一項",
    "Call Emergency Vet Now": "立即致電急診獸醫",
    "appears to be safe": "看起來是安全的",
    // Profile & Pets
    "Legal Name": "法定姓名",
    "Your legal name": "你的法定姓名",
    "Legal name is required": "請輸入法定姓名",
    "Phone number is required": "請輸入電話號碼",
    "Date of birth is required": "請輸入出生日期",
    "Save Pet Profile": "儲存寵物檔案",
    "months": "個月",
    "year": "年",
    "years": "年",
    // Premium
    "You're a Gold Member!": "你是金級會員！",
    "You're a Premium Member!": "你是高級會員！",
    "Status:": "狀態：",
    "active": "啟用中",
    "Manage": "管理",
    "Processing...": "處理中...",
    "Upgrade to": "升級為",
    "Buy": "購買",
    "Secure payments powered by Stripe": "安全付款由 Stripe 提供",
    // Premium Feature Table
    "Badge Type": "徽章類型",
    "Grey": "灰色",
    "Blue Premium": "藍色高級",
    "Gold Crown": "金色皇冠",
    "Chat Access": "聊天權限",
    "Limited": "有限",
    "Unlimited": "無限制",
    "Unlimited + Priority": "無限制 + 優先",
    "AI Vet": "AI 獸醫",
    "Text Only": "僅文字",
    "Photo + Audio": "照片 + 音訊",
    "Unlimited Media": "無限媒體",
    "Broadcast Range": "廣播範圍",
    "1 mile": "1 英里",
    "5 miles": "5 英里",
    "10 miles": "10 英里",
    "Social Filters": "社交篩選",
    "Basic": "基本",
    "Advanced": "進階",
    "Advanced + Boosts": "進階 + Boost",
    "Ghost Mode": "幽靈模式",
    "Notice Board": "公告板",
    "Priority Support": "優先支援",
    "Marketplace Priority": "市集優先",
    "Ad-free Experience": "無廣告體驗",
    // Add-ons
    "3 Star Pack": "3 顆星組合",
    "Boost your profile visibility": "提升個人曝光度",
    "Emergency Mesh Alert": "緊急網狀警報",
    "Lost pet emergency broadcast": "走失寵物緊急廣播",
    "10 AI Vet Media Credits": "10 次 AI 獸醫媒體",
    "Upload photos/videos to AI Vet": "上傳照片/影片至 AI 獸醫",
    "Family Member Slot": "家庭成員名額",
    "Add 1 family member to account": "新增 1 位家庭成員",
    "Verified Badge": "已驗證徽章",
    "One-time ID verification": "一次性身分驗證",
  },
  "zh-CN": {
    // Brand
    "app.name": "huddle",
    "app.subheadline": "宠物照护与社交",
    
    // Navigation
    "nav.home": "首页",
    "nav.social": "社交",
    "nav.chats": "聊天",
    "nav.ai_vet": "AI 兽医",
    "nav.map": "地图",
    
    // Global Header
    "header.free": "免费版",
    "header.premium": "星级会员",
    "header.upgrade": "升级",
    
    // Home
    "home.greeting": "嗨，{name}！👋",
    "home.subtitle": "一起照顾你的毛孩",
    "home.wisdom": "毛孩百科",
    "home.next_event": "下一个活动",
    
    // Social
    "social.discovery": "探索",
    "social.nearby": "附近的Huddler",
    "social.nannies": "暖心保姆",
    "social.playdates": "毛孩聚会",
    "social.animal_lovers": "动物之友",
    "social.verified": "已认证",
    "social.support": "支持",
    "social.report": "举报",
    "social.hide": "隐藏",
    "social.wave": "打招呼",
    "social.match": "双向打招呼！",
    
    // Dr. Huddle / AI Vet
    "ai.name": "Huddle AI 医生",
    "ai.online": "在线",
    "ai.analyzing": "正在分析",
    "ai.disclaimer": "Huddle AI 医生是仅供参考的人工智能助手。提供的信息可能有误。请务必寻求专业兽医意见。如有疑虑或紧急情况，请立即前往诊所。",
    "ai.placeholder": "输入消息...",
    "ai.attach_pet": "附加宠物资料",
    
    // Map
    "map.search": "搜索狗公园、兽医或朋友...",
    "map.filter_all": "全部",
    "map.filter_stray": "流浪动物",
    "map.filter_lost": "走失宠物",
    "map.filter_found": "已找到",
    "map.filter_friends": "朋友",
    "map.filter_others": "其他",
    "map.go_online": "上线",
    "map.broadcast": "紧急通报",
    "map.broadcast_remark": "通报将发送给{distance}英里内的在线用户；有效期48小时。",
    "map.call_now": "立即拨打",
    "map.navigate": "导航",
    "map.found_btn": "已找到",
    "map.remove_pin": "移除标记？",
    "map.24h": "24小时",
    
    // Chats
    "chats.title": "聊天",
    "chats.new_huddles": "新朋友",
    "chats.create_group": "创建群组",
    "chats.group_name": "群组名称",
    "chats.add_members": "添加成员",
    "chats.allow_control": "允许成员管理群组",
    
    // Settings
    "settings.title": "设置",
    "settings.profile": "个人资料",
    "settings.account_security": "账号与安全",
    "settings.personal_info": "个人信息",
    "settings.password": "密码",
    "settings.biometric": "生物识别登录",
    "settings.2fa": "双重验证",
    "settings.privacy": "隐私",
    "settings.private_account": "私人账号",
    "settings.map_visibility": "地图可见度",
    "settings.trusted_locations": "信任的位置",
    "settings.notifications": "通知",
    "settings.pause_all": "暂停所有通知",
    "settings.social_notif": "社交（打招呼/配对）",
    "settings.safety_notif": "安全（警报）",
    "settings.ai_notif": "Huddle AI 医生",
    "settings.email_notif": "电子邮件通知",
    "settings.language": "语言",
    "settings.help_support": "帮助与支持",
    "settings.report_bug": "报告问题",
    "settings.privacy_policy": "隐私政策",
    "settings.terms": "服务条款",
    "settings.deactivate": "停用账号",
    "settings.delete": "删除账号",
    "settings.logout": "登出",
    "settings.pending": "身份验证中",
    "settings.verified_badge": "认证huddler",
    
    // Profile
    "profile.edit": "编辑个人资料",
    "profile.display_name": "显示名称",
    "profile.bio": "简介",
    "profile.gender": "性别",
    "profile.genre": "性向",
    "profile.dob": "出生日期",
    "profile.height": "身高",
    "profile.degree": "最高学历",
    "profile.occupation": "职业",
    "profile.school": "学校",
    "profile.major": "专业",
    "profile.affiliation": "隶属组织",
    "profile.has_car": "有车？",
    "profile.owns_pets": "目前有养宠物？",
    "profile.show": "显示",
    
    // Pet Profile
    "pet.title": "养宠资料",
    "pet.basics": "基本资料",
    "pet.vault": "健康记录",
    "pet.lifestyle": "生活习惯",
    "pet.name": "名字",
    "pet.species": "种类",
    "pet.breed": "品种",
    "pet.gender": "性别",
    "pet.weight": "体重",
    "pet.dob": "出生日期",
    "pet.vaccinations": "疫苗接种",
    "pet.medications": "用药",
    "pet.microchip": "芯片号码",
    "pet.vet_contact": "兽医联系方式",
    "pet.temperament": "性格",
    "pet.routine": "日常作息",
    
    // Premium
    "premium.title": "Huddle 星级会员",
    "premium.unlock": "解锁完整体验",
    "premium.upgrade": "成为星级huddler",
    "premium.maybe_later": "稍后再说",
    "premium.compare": "方案比较",
    "premium.free_plan": "免费版",
    "premium.premium_plan": "星级会员",
    "premium.grey_badge": "灰色徽章",
    "premium.gold_badge": "金色徽章",
    "premium.text_ai": "文字AI",
    "premium.photo_audio_ai": "照片/语音AI",
    "premium.alert_1mi": "1英里警报",
    "premium.alert_5mi": "5英里警报",
    "premium.single_filter": "单一筛选",
    "premium.multi_filter": "多重筛选",
    "premium.ghost_mode": "隐身模式",
    "premium.featured": "精选刊登",
    

    // Nanny Booking Modal
    "booking.title": "预约保姆",
    "booking.pet_nanny": "宠物保姆",
    "booking.service_date": "服务日期",
    "booking.start_time": "开始时间",
    "booking.end_time": "结束时间",
    "booking.which_pet": "哪只宠物？",
    "booking.select_pet": "请选择宠物…",
    "booking.location": "服务地点",
    "booking.location_not_set": "请在个人资料中设置地点",
    "booking.amount": "预约金额（美元）",
    "booking.amount_note": "最低 $10 · 金额将托管至服务完成",
    "booking.amount_calculated": "价格按保姆时薪自动计算",
    "booking.cancel": "取消",
    "booking.pay": "前往付款",
    // Common
    "common.save": "保存",
    "common.cancel": "取消",
    "common.confirm": "确认",
    "common.delete": "删除",
    "common.create": "创建",
    "common.add": "添加",
    "common.remove": "移除",
    "common.close": "关闭",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功",
    "common.others": "其他",
  },
};

// Detect device language
const detectLanguage = (): Language => {
  const browserLang = navigator.language.toLowerCase();
  if (browserLang.startsWith("zh-tw") || browserLang.startsWith("zh-hant")) {
    return "zh-TW";
  } else if (browserLang.startsWith("zh")) {
    return "zh-CN";
  }
  return "en";
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("huddle_language");
    if (saved && (saved === "en" || saved === "zh-TW" || saved === "zh-CN")) {
      return saved as Language;
    }
    return detectLanguage();
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("huddle_language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language === "zh-TW" ? "zh-Hant" : language === "zh-CN" ? "zh-Hans" : "en";
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
