import { StyleSheet } from "react-native";
import { huddleButtons, huddleColors, huddleFieldStates, huddleFormControls, huddleFormFields, huddleLayout, huddleMapBroadcastFooter, huddleRadii, huddleShadows, huddleSpacing, huddleType } from "../theme/huddleDesignTokens";

export const huddleModalTokens = {
  color: {
    blue: huddleColors.blue,
    text: huddleColors.text,
    mutedText: huddleColors.mutedText,
    validationRed: huddleColors.validationRed,
    canvas: huddleColors.canvas,
    modalBackdrop: huddleColors.backdrop,
    fieldBorder: huddleColors.fieldBorder,
    fieldFocusBorder: huddleColors.fieldFocusBorder,
    fieldFocusShadow: huddleColors.fieldFocusBorder,
    fieldErrorBorder: huddleColors.fieldErrorBorder,
    fieldErrorShadow: huddleColors.fieldErrorBorder,
    neutralShadow: huddleColors.neutralShadow,
    onPrimary: huddleColors.onPrimary,
  },
  radius: {
    button: huddleRadii.button,
    field: huddleRadii.field,
    modal: huddleRadii.modal,
  },
  spacing: {
    x1: huddleSpacing.x1,
    x2: huddleSpacing.x2,
    x3: huddleSpacing.x3,
    x4: huddleSpacing.x4,
    x5: huddleSpacing.x5,
    x6: huddleSpacing.x6,
    x7: huddleSpacing.x7,
  },
  size: {
    close: huddleLayout.minTouch,
    fieldHeight: huddleLayout.fieldHeight,
    textAreaHeight: huddleSpacing.x9 + huddleSpacing.x5 + huddleSpacing.x5,
    buttonHeight: huddleButtons.base.minHeight,
  },
  type: {
    titleFamily: "Urbanist-700",
    bodyFamily: "Urbanist-500",
    labelFamily: "Urbanist-600",
    buttonFamily: "Urbanist-700",
    titleSize: huddleType.nativeHeaderTitle,
    titleLine: huddleType.nativeHeaderTitleLine,
    inputSize: huddleType.body,
    inputLine: huddleType.labelLine,
    helperSize: huddleType.helper,
    helperLine: huddleType.helperLine,
  },
} as const;

export const nativeModalStyles = StyleSheet.create({
  appModalBackdrop: {
    flex: 1,
    backgroundColor: huddleModalTokens.color.modalBackdrop,
  },
  appModalSafeArea: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: huddleModalTokens.spacing.x4,
    paddingVertical: huddleModalTokens.spacing.x4,
  },
  appModalBottomSafeArea: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "stretch",
    paddingTop: huddleSpacing.x5,
  },
  appBottomSheetEventBoundary: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
  },
  appModalMenuSafeArea: {
    flex: 1,
    alignItems: "flex-end",
    paddingTop: 110,
    paddingRight: huddleModalTokens.spacing.x4,
  },
  appModalCard: {
    maxHeight: "88%",
    overflow: "hidden",
    borderRadius: huddleModalTokens.radius.modal,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation2,
  },
  appModalCardFull: {
    flex: 1,
    overflow: "hidden",
    borderRadius: huddleModalTokens.radius.modal,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation2,
  },
  appModalSheet: {
    minHeight: 280,
    maxHeight: "88%",
    padding: huddleModalTokens.spacing.x4,
    borderTopLeftRadius: huddleRadii.sheet,
    borderTopRightRadius: huddleRadii.sheet,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation2,
  },
  appModalSheetLarge: {
    height: "86%",
    maxHeight: "86%",
    overflow: "hidden",
    borderTopLeftRadius: huddleRadii.sheet,
    borderTopRightRadius: huddleRadii.sheet,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation2,
  },
  appBottomSheet: {
    width: "100%",
    alignSelf: "stretch",
    overflow: "hidden",
    minHeight: 0,
    flexDirection: "column",
    borderTopLeftRadius: huddleRadii.sheet,
    borderTopRightRadius: huddleRadii.sheet,
    borderWidth: 1,
    borderColor: huddleColors.fieldBorder,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation2,
  },
  appBottomSheetContent: {
    maxHeight: "82%",
    minHeight: 0,
    flexShrink: 1,
  },
  appBottomSheetAutoMax: {
    maxHeight: "82%",
    minHeight: 0,
    flexShrink: 1,
  },
  appBottomSheetLarge: {
    height: "82%",
    maxHeight: "82%",
    minHeight: 0,
    flexShrink: 1,
  },
  appModalSheetPadded: {
    minHeight: 440,
    padding: huddleModalTokens.spacing.x4,
  },
  appModalSheetHeader: {
    minHeight: huddleLayout.headerHeight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: huddleModalTokens.spacing.x2,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: huddleColors.divider,
    paddingHorizontal: huddleModalTokens.spacing.x4,
    paddingTop: huddleModalTokens.spacing.x2,
    paddingBottom: huddleModalTokens.spacing.x2,
  },
  appBottomSheetHeader: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: huddleModalTokens.spacing.x2,
    paddingHorizontal: huddleSpacing.x6,
    paddingTop: huddleSpacing.x4,
  },
  appModalTitle: {
    fontFamily: "Urbanist-800",
    fontSize: huddleType.h4,
    lineHeight: huddleType.h4Line,
    color: huddleModalTokens.color.text,
  },
  appModalSheetTitle: {
    flex: 1,
    fontFamily: "Urbanist-800",
    fontSize: huddleType.h4,
    lineHeight: huddleType.h4Line,
    color: huddleModalTokens.color.text,
  },
  appModalBody: {
    fontFamily: huddleModalTokens.type.bodyFamily,
    fontSize: huddleType.body,
    lineHeight: huddleType.body * huddleType.lineNormal,
    color: huddleColors.subtext,
  },
  appModalMutedBody: {
    fontFamily: huddleModalTokens.type.bodyFamily,
    fontSize: huddleType.body,
    lineHeight: huddleType.body * huddleType.lineNormal,
    color: huddleModalTokens.color.mutedText,
  },
  appModalDragHandle: {
    position: "absolute",
    top: huddleModalTokens.spacing.x2,
    left: "50%",
    width: 40,
    height: 4,
    marginLeft: -20,
    borderRadius: huddleRadii.pill,
    backgroundColor: huddleColors.divider,
    zIndex: 2,
  },
  appModalIconButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    borderWidth: 1,
    borderColor: huddleColors.glassBorder,
    backgroundColor: huddleModalTokens.color.canvas,
  },
  appModalMenuCard: {
    width: 220,
    overflow: "hidden",
    borderRadius: huddleRadii.glass,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation1,
  },
  appModalMenuItem: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: huddleModalTokens.spacing.x3,
    paddingHorizontal: huddleModalTokens.spacing.x4,
  },
  appActionMenuCard: {
    minWidth: 176,
    maxWidth: 244,
    overflow: "hidden",
    borderRadius: huddleRadii.field,
    borderWidth: 1,
    borderColor: huddleColors.fieldBorderSoft,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation2,
  },
  appActionMenuItem: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: huddleSpacing.x2,
    paddingHorizontal: huddleSpacing.x3,
  },
  appActionMenuText: {
    flex: 1,
    fontFamily: "Urbanist-700",
    fontSize: huddleType.label,
    lineHeight: huddleType.labelLine,
    color: huddleColors.text,
  },
  appActionMenuTextDestructive: {
    color: huddleColors.validationRed,
  },
  appModalInlineCard: {
    position: "relative",
    overflow: "hidden",
    marginBottom: huddleModalTokens.spacing.x2,
    borderRadius: huddleRadii.card,
    borderWidth: 1,
    borderColor: huddleColors.fieldBorderSoft,
    backgroundColor: huddleModalTokens.color.canvas,
  },
  appModalInlineCardWrap: {
    position: "relative",
  },
  appModalIcon: {
    width: huddleLayout.minTouch,
    height: huddleLayout.minTouch,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    backgroundColor: huddleColors.premiumGoldSoft,
  },
  appModalBillingTabs: {
    height: huddleButtons.base.minHeight,
    flexDirection: "row",
    backgroundColor: huddleColors.blueLight,
  },
  appModalBillingTabsGold: {
    backgroundColor: huddleColors.coral,
  },
  appModalBillingTab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  appModalBillingTabInactive: {
    backgroundColor: huddleModalTokens.color.canvas,
  },
  appModalBillingTabText: {
    fontFamily: huddleModalTokens.type.buttonFamily,
    fontSize: huddleType.label,
    lineHeight: huddleType.labelLine,
    color: huddleModalTokens.color.onPrimary,
  },
  appContentCard: {
    overflow: "hidden",
    borderRadius: huddleRadii.glass,
    borderWidth: 1,
    borderColor: huddleColors.cardBorderSoft,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation1,
  },
  appGroupHero: {
    width: "100%",
    aspectRatio: 16 / 9,
    overflow: "hidden",
    borderTopLeftRadius: huddleRadii.glass,
    borderTopRightRadius: huddleRadii.glass,
    backgroundColor: huddleModalTokens.color.blue,
  },
  appGroupHeroImage: {
    width: "100%",
    height: "100%",
  },
  appGroupHeroFallback: {
    flex: 1,
    backgroundColor: huddleModalTokens.color.blue,
  },
  appGroupHeroTopScrim: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "28%",
  },
  appGroupHeroBottomScrim: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "60%",
  },
  appGroupHeroMembers: {
    position: "absolute",
    right: huddleModalTokens.spacing.x3,
    top: huddleModalTokens.spacing.x3,
    overflow: "hidden",
    borderRadius: huddleRadii.pill,
    paddingHorizontal: huddleModalTokens.spacing.x2 + 2,
    paddingVertical: huddleModalTokens.spacing.x1,
    backgroundColor: huddleModalTokens.color.modalBackdrop,
    fontFamily: "Urbanist-500",
    fontSize: huddleType.meta + 1,
    lineHeight: huddleType.metaLine,
    color: huddleModalTokens.color.onPrimary,
  },
  appGroupHeroCopy: {
    position: "absolute",
    left: huddleModalTokens.spacing.x4,
    right: huddleModalTokens.spacing.x4,
    bottom: huddleModalTokens.spacing.x3,
    gap: huddleModalTokens.spacing.x1,
  },
  appGroupHeroTitle: {
    fontFamily: "Urbanist-600",
    fontSize: huddleType.h4,
    lineHeight: huddleType.h4Line - 2,
    color: huddleModalTokens.color.onPrimary,
  },
  appGroupHeroMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: huddleModalTokens.spacing.x1,
  },
  appGroupHeroMeta: {
    flex: 1,
    fontFamily: "Urbanist-500",
    fontSize: huddleType.helper,
    lineHeight: huddleType.helperLine,
    color: huddleColors.profileCaptionPlaceholder,
  },
  appGroupHeroChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: huddleModalTokens.spacing.x1 + 2,
  },
  appGroupHeroChip: {
    overflow: "hidden",
    borderRadius: huddleRadii.pill,
    borderWidth: 1,
    borderColor: huddleColors.profileHeroTierBorder,
    paddingHorizontal: huddleModalTokens.spacing.x2,
    paddingVertical: huddleModalTokens.spacing.x1,
    backgroundColor: huddleColors.profileHeroTierFill,
    fontFamily: "Urbanist-500",
    fontSize: huddleType.meta,
    lineHeight: huddleType.metaLine,
    letterSpacing: 0.4,
    color: huddleModalTokens.color.onPrimary,
    textTransform: "uppercase",
  },
  appGroupMediaRail: {
    gap: huddleModalTokens.spacing.x2,
  },
  appGroupMediaThumb: {
    width: 88,
    height: 88,
    borderRadius: huddleRadii.card,
    backgroundColor: huddleColors.mutedCanvas,
  },
  appMemberSelectRow: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: huddleModalTokens.spacing.x3,
    paddingHorizontal: huddleModalTokens.spacing.x2,
  },
  appMemberSelectName: {
    flex: 1,
    fontFamily: "Urbanist-700",
    fontSize: huddleType.label,
    lineHeight: huddleType.labelLine,
    color: huddleModalTokens.color.text,
  },
  appListRow: {
    minHeight: 112,
    flexDirection: "row",
    alignItems: "center",
    gap: huddleSpacing.x4,
    paddingVertical: huddleSpacing.x4,
    paddingHorizontal: huddleSpacing.x2,
    borderBottomWidth: 1,
    borderBottomColor: huddleColors.divider,
    backgroundColor: huddleModalTokens.color.canvas,
  },
  appGroupListRow: {
    minHeight: 126,
    flexDirection: "row",
    alignItems: "center",
    gap: huddleSpacing.x4,
    paddingVertical: huddleSpacing.x4,
    paddingHorizontal: huddleSpacing.x2,
    backgroundColor: huddleModalTokens.color.canvas,
  },
  appEmptyWrap: {
    width: "100%",
    alignItems: "center",
    alignSelf: "center",
    paddingVertical: huddleSpacing.x4,
    paddingHorizontal: huddleSpacing.x2,
  },
  appTopSegmentButton: {
    flex: 1,
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    paddingHorizontal: huddleSpacing.x2,
  },
  appTopSegmentButtonActive: {
    backgroundColor: huddleColors.blue,
    ...huddleShadows.photoControl,
  },
  appUnderlineTab: {
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: huddleSpacing.x3 + huddleSpacing.x1 / 2,
  },
  appPillTab: {
    minHeight: 32,
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    paddingHorizontal: huddleSpacing.x4,
    backgroundColor: huddleColors.mutedCanvas,
    borderWidth: 0,
  },
  appPillTabActive: {
    borderColor: huddleColors.blue,
    backgroundColor: huddleColors.blue,
  },
  appOptionChip: {
    minHeight: 32,
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    paddingHorizontal: huddleSpacing.x3,
    borderWidth: 1,
    borderColor: huddleColors.fieldBorderSoft,
    backgroundColor: huddleModalTokens.color.canvas,
  },
  appOptionChipActive: {
    borderColor: huddleColors.blue,
    backgroundColor: huddleColors.blue,
  },
  appOptionCard: {
    flex: 1,
    minHeight: 86,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: huddleSpacing.x2,
    borderRadius: huddleRadii.field,
    borderWidth: 1,
    borderColor: huddleColors.fieldBorderSoft,
    padding: huddleSpacing.x3,
    backgroundColor: huddleModalTokens.color.canvas,
  },
  appOptionCardActive: {
    borderColor: huddleColors.blue,
    backgroundColor: huddleColors.blue,
  },
  appLoadMoreButton: {
    alignSelf: "center",
    minHeight: 38,
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    paddingHorizontal: huddleSpacing.x4,
    borderWidth: 1,
    borderColor: huddleColors.fieldBorderSoft,
  },
  appPrimaryPillButton: {
    ...huddleButtons.base,
    ...huddleButtons.primary,
    minHeight: 44,
    borderRadius: huddleRadii.pill,
  },
  appModalInlineCardBody: {
    gap: huddleModalTokens.spacing.x1,
    paddingHorizontal: huddleModalTokens.spacing.x3,
    paddingVertical: huddleModalTokens.spacing.x2,
  },
  appModalInlineCardClose: {
    position: "absolute",
    top: huddleModalTokens.spacing.x2,
    right: huddleModalTokens.spacing.x2,
    zIndex: 5,
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    backgroundColor: huddleColors.glassOverlay,
    ...huddleShadows.photoControl,
  },
  appModalStackCard: {
    gap: huddleModalTokens.spacing.x1,
    marginBottom: huddleModalTokens.spacing.x2,
  },
  appModalDescriptionCard: {
    borderRadius: huddleRadii.glass,
    borderWidth: 1,
    borderColor: huddleColors.glassBorder,
    paddingHorizontal: huddleModalTokens.spacing.x4,
    paddingVertical: huddleModalTokens.spacing.x3,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation1,
  },
  appModalCompactSecondaryButton: {
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    paddingHorizontal: huddleModalTokens.spacing.x4,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.photoControl,
  },
  appModalCompactIconButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    backgroundColor: huddleColors.blueSoft,
  },
  appModalSocialIconButton: {
    minHeight: 34,
    minWidth: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
  },
  appModalShareCard: {
    maxWidth: "90%",
    overflow: "hidden",
    borderRadius: huddleRadii.card,
    borderWidth: 1,
    borderColor: huddleColors.fieldFocusBorder,
    backgroundColor: huddleColors.blueSoft,
  },
  appModalShareCardMine: {
    backgroundColor: huddleColors.blueSoft,
  },
  appModalShareCardBody: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: huddleModalTokens.spacing.x2,
    padding: huddleModalTokens.spacing.x1,
  },
  appModalComposerSurface: {
    gap: huddleModalTokens.spacing.x2,
    paddingHorizontal: huddleModalTokens.spacing.x3,
    paddingTop: huddleModalTokens.spacing.x2,
    paddingBottom: huddleModalTokens.spacing.x4,
    borderTopWidth: 1,
    borderTopColor: huddleColors.divider,
    backgroundColor: huddleColors.glassOverlay,
  },
  appModalComposerTray: {
    flex: 1,
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: huddleModalTokens.spacing.x2,
    borderRadius: huddleRadii.field,
    borderWidth: 1,
    borderColor: huddleColors.fieldBorderStrong,
    paddingHorizontal: huddleModalTokens.spacing.x2,
    backgroundColor: huddleColors.canvas,
    shadowColor: huddleModalTokens.color.neutralShadow,
    shadowOpacity: huddleFormFields.shadowOpacity,
    shadowRadius: huddleFormFields.shadowRadius,
    shadowOffset: { width: 2, height: 2 },
  },
  appModalComposerTrayFocused: {
    ...huddleFieldStates.focused,
    borderWidth: 2,
  },
  appModalComposerInput: {
    flex: 1,
    height: 44,
    minHeight: 44,
    maxHeight: 96,
    borderWidth: 0,
    paddingHorizontal: huddleModalTokens.spacing.x1,
    paddingVertical: 0,
    backgroundColor: "transparent",
    shadowOpacity: 0,
    elevation: 0,
  },
  appMatchCloseButton: {
    position: "absolute",
    right: huddleModalTokens.spacing.x4,
    zIndex: 20,
    width: huddleModalTokens.spacing.x6,
    height: huddleModalTokens.spacing.x6,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    backgroundColor: huddleColors.glassBorder,
    ...huddleShadows.glassElevation1,
  },
  appMatchComposerChrome: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    gap: huddleModalTokens.spacing.x2,
    borderRadius: huddleRadii.glass,
    borderWidth: 1,
    borderColor: huddleColors.glassBorder,
    padding: huddleModalTokens.spacing.x2,
    backgroundColor: huddleColors.glassChrome,
    ...huddleShadows.glassElevation2,
  },
  appMatchComposerSend: {
    width: huddleLayout.minTouch,
    height: huddleLayout.minTouch,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: huddleRadii.pill,
    backgroundColor: huddleModalTokens.color.blue,
    ...huddleShadows.photoControl,
  },
  appModalClose: {
    position: "absolute",
    top: huddleModalTokens.spacing.x3,
    right: huddleModalTokens.spacing.x3,
    zIndex: 5,
    width: huddleModalTokens.size.close,
    height: huddleModalTokens.size.close,
    alignItems: "center",
    justifyContent: "center",
  },
  appModalScrollContent: {
    paddingHorizontal: huddleSpacing.x6,
    paddingTop: huddleModalTokens.spacing.x3,
    paddingBottom: huddleSpacing.x8,
  },
  appModalScrollContentEdgeToEdge: {
    paddingHorizontal: 0,
  },
  appModalScroll: {
    flexGrow: 0,
    flexShrink: 1,
    minHeight: 0,
  },
  appBottomSheetScroll: {
    flexGrow: 0,
    flexShrink: 1,
    minHeight: 0,
  },
  appBottomSheetScrollFill: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
  },
  appModalFixedFooter: {
    width: "100%",
    alignSelf: "stretch",
    flexShrink: 0,
    gap: huddleMapBroadcastFooter.gap,
    paddingHorizontal: huddleMapBroadcastFooter.horizontalPadding,
    paddingTop: huddleMapBroadcastFooter.topPadding,
    paddingBottom: huddleMapBroadcastFooter.bottomPadding,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: huddleColors.divider,
    backgroundColor: huddleModalTokens.color.canvas,
  },
  appModalField: {
    height: huddleModalTokens.size.fieldHeight,
    borderWidth: 1,
    borderColor: huddleModalTokens.color.fieldBorder,
    borderRadius: huddleModalTokens.radius.field,
    paddingHorizontal: huddleModalTokens.spacing.x4,
    paddingTop: 0,
    paddingBottom: 0,
    fontFamily: huddleModalTokens.type.bodyFamily,
    fontSize: huddleModalTokens.type.inputSize,
    lineHeight: huddleModalTokens.type.inputLine,
    includeFontPadding: false,
    color: huddleModalTokens.color.text,
    textAlignVertical: "center",
    backgroundColor: huddleColors.glassChrome,
    shadowColor: huddleModalTokens.color.neutralShadow,
    shadowOpacity: huddleFormFields.shadowOpacity,
    shadowRadius: huddleFormFields.shadowRadius,
    shadowOffset: { width: huddleFormFields.shadowOffset, height: huddleFormFields.shadowOffset },
    elevation: 1,
  },
  appModalFieldFocused: {
    ...huddleFieldStates.focused,
  },
  appModalFieldError: {
    ...huddleFieldStates.error,
  },
  appModalTextArea: {
    height: huddleModalTokens.size.textAreaHeight,
    maxHeight: huddleModalTokens.size.textAreaHeight,
    paddingBottom: huddleModalTokens.spacing.x3,
    paddingTop: huddleModalTokens.spacing.x3,
  },
  appModalFieldBlock: {
    gap: huddleModalTokens.spacing.x1 + 2,
  },
  appModalFieldLabel: {
    paddingLeft: huddleModalTokens.spacing.x1,
    fontFamily: "Urbanist-700",
    fontSize: huddleFormFields.compactLabelSize,
    lineHeight: huddleFormFields.compactLabelLine,
    color: huddleModalTokens.color.text,
  },
  appModalSelectTrigger: {
    minHeight: huddleFormFields.compactFieldHeight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: huddleModalTokens.spacing.x2,
    borderRadius: huddleFormFields.compactRadius,
    borderWidth: 1,
    borderColor: huddleModalTokens.color.fieldBorder,
    paddingHorizontal: huddleModalTokens.spacing.x3,
    backgroundColor: huddleModalTokens.color.canvas,
    shadowColor: huddleModalTokens.color.neutralShadow,
    shadowOpacity: huddleFormFields.shadowOpacity,
    shadowRadius: huddleFormFields.shadowRadius,
    shadowOffset: { width: huddleFormFields.shadowOffset, height: huddleFormFields.shadowOffset },
    elevation: 1,
  },
  appModalSelectText: {
    flex: 1,
    fontFamily: "Urbanist-500",
    fontSize: huddleFormFields.valueSize,
    lineHeight: huddleFormFields.valueLine,
    color: huddleModalTokens.color.text,
  },
  appModalSelectPlaceholder: {
    color: huddleModalTokens.color.mutedText,
  },
  appModalSelectMenu: {
    maxHeight: huddleFormControls.select.menuMaxHeight,
    overflow: "hidden",
    marginTop: huddleModalTokens.spacing.x2,
    borderRadius: huddleFormControls.select.menuRadius,
    borderWidth: 1,
    borderColor: huddleFormControls.select.menuBorderColor,
    padding: huddleFormControls.select.menuPadding,
    backgroundColor: huddleModalTokens.color.canvas,
    ...huddleShadows.glassElevation1,
  },
  appModalSelectOption: {
    minHeight: huddleFormControls.select.optionMinHeight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: huddleModalTokens.spacing.x2,
    borderRadius: huddleFormControls.select.optionRadius,
    paddingHorizontal: huddleFormControls.select.optionPaddingHorizontal,
    paddingVertical: huddleFormControls.select.optionPaddingVertical,
  },
  appModalSelectOptionText: {
    flex: 1,
    fontFamily: "Urbanist-500",
    fontSize: huddleType.label,
    lineHeight: huddleType.labelLine,
    color: huddleModalTokens.color.text,
  },
  appModalSelectOptionTextActive: {
    fontFamily: "Urbanist-700",
    color: huddleModalTokens.color.blue,
  },
  appModalError: {
    fontFamily: huddleModalTokens.type.labelFamily,
    fontSize: huddleModalTokens.type.helperSize,
    lineHeight: huddleModalTokens.type.helperLine,
    color: huddleModalTokens.color.validationRed,
  },
  appModalActionRow: {
    flexDirection: "row",
    gap: huddleModalTokens.spacing.x3,
    paddingTop: huddleModalTokens.spacing.x1,
  },
  appModalActionItem: {
    flex: 1,
    minWidth: 0,
  },
  appModalPrimaryButton: {
    width: "100%",
    flexGrow: 0,
    flexShrink: 0,
    ...huddleButtons.base,
    ...huddleButtons.primary,
  },
  appModalSecondaryButton: {
    width: "100%",
    flexGrow: 0,
    flexShrink: 0,
    ...huddleButtons.base,
    ...huddleButtons.secondary,
  },
  appModalDestructiveButton: {
    width: "100%",
    flexGrow: 0,
    flexShrink: 0,
    ...huddleButtons.base,
    ...huddleButtons.destructive,
  },
  appStarUpgradeCard: {
    width: "100%",
    maxWidth: 390,
    maxHeight: "92%",
    overflow: "hidden",
    borderRadius: huddleRadii.glass,
    borderWidth: 1,
    borderColor: huddleColors.glassBorder,
    backgroundColor: huddleColors.blueLight,
    ...huddleShadows.glassElevation2,
  },
  appStarUpgradeCardGold: {
    backgroundColor: huddleColors.coral,
  },
  appStarHeadline: {
    fontFamily: "Urbanist-800",
    fontSize: huddleType.h3,
    lineHeight: huddleType.h3Line,
    color: huddleModalTokens.color.onPrimary,
  },
  appStarSubheadline: {
    fontFamily: "Urbanist-500",
    fontSize: huddleType.helper,
    lineHeight: huddleType.helperLine,
    color: huddleModalTokens.color.onPrimary,
    opacity: 0.8,
  },
  appStarPrice: {
    paddingTop: huddleModalTokens.spacing.x4,
    fontFamily: "Urbanist-800",
    fontSize: 30,
    lineHeight: 36,
    color: huddleModalTokens.color.onPrimary,
  },
  appStarPriceSuffix: {
    fontFamily: "Urbanist-500",
    fontSize: huddleType.label,
    lineHeight: huddleType.labelLine,
    color: huddleModalTokens.color.onPrimary,
    opacity: 0.82,
  },
  appStarAnnualPriceRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: huddleModalTokens.spacing.x2,
    paddingTop: huddleModalTokens.spacing.x2,
  },
  appStarStruckPrice: {
    fontFamily: "Urbanist-500",
    fontSize: huddleType.label,
    lineHeight: huddleType.labelLine,
    color: huddleModalTokens.color.onPrimary,
    textDecorationLine: "line-through",
    opacity: 0.72,
  },
  appStarAnnualNote: {
    fontFamily: "Urbanist-500",
    fontSize: huddleType.helper,
    lineHeight: huddleType.helperLine,
    color: huddleModalTokens.color.onPrimary,
    opacity: 0.82,
  },
  appStarDivider: {
    height: 1,
    marginVertical: huddleModalTokens.spacing.x4,
    backgroundColor: huddleColors.profileHeroTierBorder,
  },
  appStarFeatureRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: huddleModalTokens.spacing.x3,
    paddingVertical: huddleModalTokens.spacing.x2 + 2,
  },
  appStarFeatureCopy: {
    flex: 1,
    gap: 2,
  },
  appStarFeatureTitle: {
    fontFamily: "Urbanist-700",
    fontSize: huddleFormFields.compactLabelSize,
    lineHeight: huddleFormFields.compactLabelLine - 2,
    color: huddleModalTokens.color.onPrimary,
  },
  appStarFeatureText: {
    fontFamily: "Urbanist-500",
    fontSize: huddleType.meta + 1,
    lineHeight: huddleType.metaLine,
    color: huddleModalTokens.color.onPrimary,
    opacity: 0.82,
  },
  appStarCheckoutButton: {
    minHeight: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: huddleModalTokens.spacing.x5,
    borderRadius: huddleModalTokens.radius.button,
    backgroundColor: huddleModalTokens.color.canvas,
  },
  appStarCheckoutButtonText: {
    fontFamily: "Urbanist-700",
    fontSize: huddleFormFields.valueSize,
    lineHeight: huddleFormFields.valueLine,
    color: huddleColors.blueLight,
  },
  appStarCheckoutButtonTextGold: {
    color: huddleColors.coral,
  },
  appStarLaterButton: {
    minHeight: huddleModalTokens.spacing.x6,
    alignItems: "center",
    justifyContent: "center",
    marginTop: huddleModalTokens.spacing.x2,
  },
  appStarLaterText: {
    fontFamily: "Urbanist-600",
    fontSize: huddleType.helper,
    lineHeight: huddleType.helperLine,
    color: huddleModalTokens.color.onPrimary,
    opacity: 0.65,
  },
  appStarInactiveTextPlus: {
    color: huddleModalTokens.color.blue,
  },
  appStarInactiveTextGold: {
    color: huddleColors.coral,
  },
  appStarDiscountPill: {
    overflow: "hidden",
    borderRadius: huddleRadii.pill,
    paddingHorizontal: huddleModalTokens.spacing.x1 + 2,
    paddingVertical: 2,
    backgroundColor: huddleModalTokens.color.blue,
    fontFamily: "Urbanist-600",
    fontSize: huddleType.meta,
    lineHeight: huddleType.metaLine,
    color: huddleModalTokens.color.onPrimary,
  },
  appStarDiscountPillGold: {
    backgroundColor: huddleColors.coral,
  },
  pressed: {
    ...huddleButtons.pressed,
  },
  disabled: {
    ...huddleButtons.disabled,
  },
});
