-- Canonical profiles column alignment for APP_MASTER_SPEC v1.1
-- Adds missing columns without mutating existing data.

alter table public.profiles
  add column if not exists display_name text,
  add column if not exists legal_name text,
  add column if not exists phone text,
  add column if not exists avatar_url text,
  add column if not exists bio text,
  add column if not exists gender_genre text,
  add column if not exists orientation text,
  add column if not exists dob date,
  add column if not exists height numeric,
  add column if not exists weight numeric,
  add column if not exists weight_unit text,
  add column if not exists degree text,
  add column if not exists school text,
  add column if not exists major text,
  add column if not exists affiliation text,
  add column if not exists occupation text,
  add column if not exists pet_experience text[],
  add column if not exists experience_years int,
  add column if not exists relationship_status text,
  add column if not exists has_car boolean default false,
  add column if not exists languages text[],
  add column if not exists location_name text,
  add column if not exists is_verified boolean default false,
  add column if not exists user_role text default 'user',
  add column if not exists tier text default 'free',
  add column if not exists subscription_status text,
  add column if not exists stars_count int default 0,
  add column if not exists mesh_alert_count int default 0,
  add column if not exists media_credits int default 0,
  add column if not exists family_slots int default 0,
  add column if not exists onboarding_completed boolean default false,
  add column if not exists owns_pets boolean default false,
  add column if not exists social_availability text,
  add column if not exists availability_status text,
  add column if not exists show_gender boolean default true,
  add column if not exists show_orientation boolean default true,
  add column if not exists show_age boolean default true,
  add column if not exists show_height boolean default true,
  add column if not exists show_weight boolean default true,
  add column if not exists show_academic boolean default true,
  add column if not exists show_affiliation boolean default true,
  add column if not exists show_occupation boolean default true,
  add column if not exists show_bio boolean default true,
  add column if not exists last_lat double precision,
  add column if not exists last_lng double precision,
  add column if not exists care_circle uuid[],
  add column if not exists verification_status text default 'pending',
  add column if not exists verification_comment text,
  add column if not exists verification_document_url text;

alter table public.pets
  add column if not exists neutered_spayed boolean default false,
  add column if not exists clinic_name text,
  add column if not exists preferred_vet text,
  add column if not exists phone_no text,
  add column if not exists next_vaccination_reminder date;
